### ISSUE TITLE
java.lang.NoClassDefFoundError: org/json/simple/parser/ParseException

### ISSUE THREAD

**Issue by VitaliyBoyko** [magento/magento2-phpstorm-plugin#1184]
**Describe the bug** (*)

```
java.lang.NoClassDefFoundError: org/json/simple/parser/ParseException
	at com.magento.idea.magento2plugin.actions.generation.dialog.NewModuleDialog.generateComposerJson(NewModuleDialog.java:207)
	at com.magento.idea.magento2plugin.actions.generation.dialog.NewModuleDialog.generateFiles(NewModuleDialog.java:189)
	at com.magento.idea.magento2plugin.actions.generation.dialog.NewModuleDialog.onOK(NewModuleDialog.java:183)
	at com.magento.idea.magento2plugin.actions.generation.dialog.NewModuleDialog.lambda$new$0(NewModuleDialog.java:144)
	at java.desktop/javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1972)
	at java.desktop/javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2313)
	at java.desktop/javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:405)
	at java.desktop/javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:262)
	at java.desktop/javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:279)
	at java.desktop/java.awt.Component.processMouseEvent(Component.java:6648)
	at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3392)
	at java.desktop/java.awt.Component.processEvent(Component.java:6413)
	at java.desktop/java.awt.Container.processEvent(Container.java:2266)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5022)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2324)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4854)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4948)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4575)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4516)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2310)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2802)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4854)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:781)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:730)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:724)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:97)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:754)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:752)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:751)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:918)
	at com.intellij.ide.IdeEventQueue.dispatchMouseEvent(IdeEventQueue.java:840)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:763)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$6(IdeEventQueue.java:450)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:791)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$7(IdeEventQueue.java:449)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:105)
	at com.intellij.ide.IdeEventQueue.performActivity(IdeEventQueue.java:624)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:447)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:881)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:493)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:121)
	at java.desktop/java.awt.WaitDispatchSupport$2.run(WaitDispatchSupport.java:191)
	at java.desktop/java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:236)
	at java.desktop/java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:234)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:318)
	at java.desktop/java.awt.WaitDispatchSupport.enter(WaitDispatchSupport.java:234)
	at java.desktop/java.awt.Dialog.show(Dialog.java:1080)
	at java.desktop/java.awt.Component.show(Component.java:1749)
	at java.desktop/java.awt.Component.setVisible(Component.java:1696)
	at java.desktop/java.awt.Window.setVisible(Window.java:1042)
	at java.desktop/java.awt.Dialog.setVisible(Dialog.java:1016)
	at com.magento.idea.magento2plugin.actions.generation.dialog.AbstractDialog.setVisible(AbstractDialog.java:277)
	at com.magento.idea.magento2plugin.actions.generation.dialog.NewModuleDialog.open(NewModuleDialog.java:361)
	at com.magento.idea.magento2plugin.actions.generation.NewModuleAction.invoke(NewModuleAction.java:53)
	at com.magento.idea.magento2plugin.actions.generation.NewModuleAction.actionPerformed(NewModuleAction.java:47)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.doPerformActionOrShowPopup(ActionUtil.java:315)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.lambda$performActionDumbAwareWithCallbacks$4(ActionUtil.java:294)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performDumbAwareWithCallbacks(ActionUtil.java:337)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAwareWithCallbacks(ActionUtil.java:294)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem.lambda$performAction$4(ActionMenuItem.java:293)
	at com.intellij.openapi.wm.impl.FocusManagerImpl.runOnOwnContext(FocusManagerImpl.java:227)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem.performAction(ActionMenuItem.java:286)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem.lambda$new$0(ActionMenuItem.java:67)
	at java.desktop/javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1972)
	at com.intellij.openapi.a
```

**To Reproduce** (*)

1. Create a New Module

**Expected behavior** (*)

**Screenshots**

**Please complete the following information:** (*)

 - OS: Linux 5.15.0-47-generic
 - PhpStorm/Intellij version: 2022.2.1
 - Plugin Version: 4.4.0

**Additional context**

**Comment by bohdan-harniuk** [comment]
Hello, @VitaliyBoyko!

I've investigated this issue. There is no bug. 

How to get it (actual only for testing in the local env.):

1. Goto `PhpStorm > Preferences > Plugins > Install Plugin from Disk...`
2. choose built jar file at `PROJECT_ROOT/build/libs/magento2-4.4.0.jar`
3. restart IDE
4. create a New Module

**Result:**

<img width="901" alt="Screenshot 2022-09-13 at 22 50 02" src="https://user-images.githubusercontent.com/31848341/189995937-33c8f93a-f784-4487-8ec7-ffcdda86e5df.png">

How we should test everything in the local env.:

1. Goto `PhpStorm > Preferences > Plugins > Install Plugin from Disk...`
2. choose built jar file at `PROJECT_ROOT/build/distributions/com.magento.idea.magento2plugin-4.4.0.zip`
3. restart IDE
4. create a New Module

**Result:**

<img width="386" alt="Screenshot 2022-09-13 at 22 52 10" src="https://user-images.githubusercontent.com/31848341/189996299-90888e34-442f-4c25-ab67-5dd9129aecd1.png">

**Reason:**

Because generated *.jar archive doesn’t contain plugin dependencies. It is used only for sandbox, not for distribution.
To get ZIP in the `distributions` folder, run the `build` task.

Regards,
