### ISSUE TITLE
[Bug] Throwable: unable to get stub builder for file with file

### ISSUE THREAD

**Issue by Mr-Leonerrr** [magento/magento2-phpstorm-plugin#1222]
**Describe the bug** (*)

```
java.lang.Throwable: unable to get stub builder for file with file = file:////wsl$/Ubuntu-20.04/home/omnipro/Sites/dospinos-last/dev/tests/acceptance/tests/_data/catalog_import_products_url_rewrite.csv, file type = com.intellij.database.csv.CsvFileType@31ea4ee3, indexed file type = com.intellij.database.csv.CsvFileType@31ea4ee3, , stubBindingRoot = PsiPlainTextFileImpl, languages = [TEXT], fileTypes = [CSV/TSV], files = [PsiPlainTextFileImpl], roots = [], indexingInfo = null, isTooLarge = false
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:184)
	at com.intellij.psi.stubs.StubProcessingHelperBase.handleNonPsiStubs(StubProcessingHelperBase.java:116)
	at com.intellij.psi.stubs.StubProcessingHelperBase.processStubsInFile(StubProcessingHelperBase.java:67)
	at com.intellij.psi.stubs.StubIndexEx.lambda$processElements$4(StubIndexEx.java:138)
	at com.intellij.psi.stubs.StubIndexEx.processElements(StubIndexEx.java:185)
	at com.intellij.psi.stubs.StubIndex.getElements(StubIndex.java:99)
	at com.intellij.psi.stubs.StubIndex.getElements(StubIndex.java:87)
	at com.jetbrains.php.PhpIndexImpl.getElements(PhpIndexImpl.java:659)
	at com.jetbrains.php.PhpIndexImpl.getByName(PhpIndexImpl.java:1111)
	at com.jetbrains.php.PhpIndexImpl.getByFQN(PhpIndexImpl.java:1086)
	at com.jetbrains.php.PhpIndexImpl.getByFqnCacheAware(PhpIndexImpl.java:1172)
	at com.jetbrains.php.PhpIndexImpl.getClassesByFQNInternal(PhpIndexImpl.java:1166)
	at com.jetbrains.php.PhpIndexImpl.getAnyByFQN(PhpIndexImpl.java:1209)
	at com.jetbrains.php.lang.psi.resolve.types.PhpType.findSuper(PhpType.java:909)
	at com.jetbrains.php.lang.psi.resolve.types.PhpType.findSuper(PhpType.java:887)
	at com.jetbrains.php.lang.psi.elements.impl.MethodReferenceImpl.lambda$createComparator$4(MethodReferenceImpl.java:190)
	at java.base/java.util.function.BinaryOperator.lambda$minBy$0(BinaryOperator.java:59)
	at java.base/java.util.stream.ReduceOps$2ReducingSink.accept(ReduceOps.java:123)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.reduce(ReferencePipeline.java:662)
	at java.base/java.util.stream.ReferencePipeline.min(ReferencePipeline.java:703)
	at com.jetbrains.php.lang.psi.elements.impl.MethodReferenceImpl.findBaseMethodInHierarchy(MethodReferenceImpl.java:177)
	at com.jetbrains.php.lang.psi.elements.impl.MethodReferenceImpl.resolve(MethodReferenceImpl.java:149)
	at com.jetbrains.php.lang.psi.elements.impl.MethodReferenceImpl.resolve(MethodReferenceImpl.java:142)
	at com.magento.idea.magento2uct.inspections.php.CallMethodInspection$1.visitPhpMethodReference(CallMethodInspection.java:38)
	at com.jetbrains.php.lang.psi.elements.impl.MethodReferenceImpl.accept(MethodReferenceImpl.java:44)
	at com.jetbrains.php.lang.psi.elements.impl.PhpASTElementImpl.accept(PhpASTElementImpl.java:26)
	at com.intellij.codeInsight.daemon.impl.InspectionRunner.lambda$processInOrder$10(InspectionRunner.java:317)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1154)
	at com.intellij.codeInsight.daemon.impl.InspectionRunner.lambda$processInOrder$11(InspectionRunner.java:325)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:174)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:215)
	at com.intellij.codeInsight.daemon.impl.InspectionRunner.lambda$processInOrder$12(InspectionRunner.java:331)
	at com.intellij.util.AstLoadingFilter.forceAllowTreeLoading(AstLoadingFilter.java:159)
	at com.intellij.util.AstLoadingFilter.forceAllowTreeLoading(AstLoadingFilter.java:151)
	at com.intellij.codeInsight.daemon.impl.InspectionRunner.lambda$processInOrder$13(InspectionRunner.java:294)
	at com.intellij.util.AstLoadingFilter.disallowTreeLoading(AstLoadingFilter.java:130)
	at com.intellij.util.AstLoadingFilter.disallowTreeLoading(AstLoadingFilter.java:119)
	at com.intellij.codeInsight.daemon.impl.InspectionRunner.lambda$processInOrder$14(InspectionRunner.java:294)
	at com.intellij.concurrency.JobLauncherImpl$1MyProcessQueueTask.lambda$call$0(JobLauncherImpl.java:297)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$12(CoreProgressManager.java:608)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:683)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:639)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:607)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:60)
	at com.intellij.concurrency.JobLauncherImpl$1MyProcessQueueTask.call(JobLauncherImpl.java:282)
	at com.intellij.concurrency.JobLauncherImpl.processQueue(JobLauncherImpl.java:350)
	at com.intellij.codeInsight.daemon.impl.InspectionRunner.processInOrder(InspectionRunner.java:293)
	at com.intellij.codeInsight.daemon.impl.InspectionRunner.visitElements(InspectionRunner.java:268)
	at com.intellij.codeInsight.daemon.impl.InspectionRunner.lambda$inspect$5(InspectionRunner.java:121)
	at com.intellij.codeInspection.InspectionEngine.withSession(InspectionEngine.java:226)
	at com.intellij.codeInsight.daemon.impl.InspectionRunner.inspect(InspectionRunner.java:109)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.collectInformationWithProgress(LocalInspectionsPass.java:131)
	at com.intellij.codeInsight.daemon.impl.ProgressableTextEditorHighlightingPass.doCollectInformation(ProgressableTextEditorHighlightingPass.java:97)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:57)
	at 
```

**Please complete the following information:** (*)

 - OS: Windows 10 10.0
 - PhpStorm/Intellij version: 2022.2.2
 - Plugin Version: 4.4.0

**Comment by makzef** [comment]
@magento I am working on this

**Comment by makzef** [comment]
Hello @Mr-Leonerrr !
Thanks for your report.

Current issue is similar to the other issue https://github.com/magento/magento2-phpstorm-plugin/issues/1220.
We can't reproduce that issue properly and this one as well. But some changes were implemented to avoid such errors in https://github.com/magento/magento2-phpstorm-plugin/pull/1234, currently waiting for review. Changes in that PR should cover this case.

@bohdan-harniuk issue is related to https://github.com/magento/magento2-phpstorm-plugin/issues/1220 and will be fix as part of another task.

Thank you.

**Comment by VitaliyBoyko** [comment]
Duplicate
