### ISSUE TITLE
java.lang.IllegalArgumentException: Element from alien project: 18680713 expected: 726865022; basePathEquals: false; nameEquals: false

### ISSUE THREAD

**Issue by Bashev** [magento/magento2-phpstorm-plugin#1257]
**Describe the bug** (*)

```
java.lang.IllegalArgumentException: Element from alien project: 18680713 expected: 726865022; basePathEquals: false; nameEquals: false
	at com.intellij.psi.impl.smartPointers.SmartPointerManagerImpl.ensureMyProject(SmartPointerManagerImpl.java:104)
	at com.intellij.psi.impl.smartPointers.SmartPointerManagerImpl.createSmartPsiElementPointer(SmartPointerManagerImpl.java:84)
	at com.intellij.psi.impl.smartPointers.SmartPointerManagerImpl.createSmartPsiElementPointer(SmartPointerManagerImpl.java:75)
	at com.intellij.psi.impl.smartPointers.SmartPointerManagerImpl.createSmartPsiElementPointer(SmartPointerManagerImpl.java:70)
	at com.intellij.codeInsight.navigation.NavigationGutterIconBuilder.calcPsiTargets(NavigationGutterIconBuilder.java:361)
	at com.intellij.codeInsight.navigation.NavigationGutterIconBuilder.createPointersThunk(NavigationGutterIconBuilder.java:341)
	at com.intellij.codeInsight.navigation.NavigationGutterIconBuilder.createGutterIconRenderer(NavigationGutterIconBuilder.java:288)
	at com.intellij.codeInsight.navigation.NavigationGutterIconBuilder.createLineMarkerInfo(NavigationGutterIconBuilder.java:240)
	at com.magento.idea.magento2plugin.linemarker.php.PluginLineMarkerProvider.collectSlowLineMarkers(PluginLineMarkerProvider.java:88)
	at com.intellij.codeInsight.daemon.impl.LineMarkersPass.queryProviders(LineMarkersPass.java:224)
	at com.intellij.codeInsight.daemon.impl.LineMarkersPass.lambda$doCollectInformation$3(LineMarkersPass.java:104)
	at com.intellij.codeInsight.daemon.impl.Divider.divideInsideAndOutsideInOneRoot(Divider.java:95)
	at com.intellij.codeInsight.daemon.impl.LineMarkersPass.doCollectInformation(LineMarkersPass.java:99)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:57)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$1(PassExecutorService.java:405)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1086)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$2(PassExecutorService.java:397)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$13(CoreProgressManager.java:591)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:666)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:622)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:590)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:60)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.doRun(PassExecutorService.java:396)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$run$0(PassExecutorService.java:372)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:174)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:182)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:370)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:181)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)


```

**To Reproduce** (*)

**Expected behavior** (*)

**Screenshots**

**Please complete the following information:** (*)

 - OS: Windows 11 10.0
 - PhpStorm/Intellij version: 2022.3
 - Plugin Version: 4.4.0

**Additional context**

**Comment by VitaliyBoyko** [comment]
Hi 👋  @Bashev 

Could you please add more steps to reproduce?

What I understand from the trace: you have 2 projects and a line marker is being created for an element in another project.
I've tried to reproduce it but no luck:
<img width="1034" alt="Screenshot 2022-12-17 at 11 55 57" src="https://user-images.githubusercontent.com/20116393/208236457-4e2a7b9b-9aa6-4b2a-b6ef-42230748ff1a.png">

**Comment by VitaliyBoyko** [comment]
Closing due to inactivity
