### ISSUE TITLE
Bug Report 2022/12/08

### ISSUE THREAD

**Issue by Ruslan-Pundyk** [magento/magento2-phpstorm-plugin#1258]
**Describe the bug** (*)

```
com.intellij.util.io.PersistentEnumeratorBase$CorruptedException: PersistentEnumerator storage corrupted /home/ruslan/.cache/JetBrains/PhpStorm2022.3/index/fileincludes/.perFileVersion/indexed_versions/indexed_versions
	at com.intellij.util.io.PersistentEnumeratorBase.catchCorruption(PersistentEnumeratorBase.java:628)
	at com.intellij.util.io.PersistentEnumeratorBase.doEnumerate(PersistentEnumeratorBase.java:272)
	at com.intellij.util.io.PersistentEnumeratorBase.tryEnumerate(PersistentEnumeratorBase.java:263)
	at com.intellij.util.io.PersistentMapImpl.doGet(PersistentMapImpl.java:587)
	at com.intellij.util.io.PersistentMapImpl.get(PersistentMapImpl.java:549)
	at com.intellij.util.io.PersistentHashMap.get(PersistentHashMap.java:169)
	at com.intellij.util.indexing.impl.perFileVersion.PersistentSubIndexerVersionEnumerator$MyEnumerator.enumerate(PersistentSubIndexerVersionEnumerator.java:22)
	at com.intellij.util.io.CachingEnumerator.enumerate(CachingEnumerator.java:75)
	at com.intellij.util.indexing.impl.perFileVersion.PersistentSubIndexerVersionEnumerator.enumerate(PersistentSubIndexerVersionEnumerator.java:60)
	at com.intellij.util.indexing.impl.perFileVersion.PersistentSubIndexerRetriever.getFileIndexerId(PersistentSubIndexerRetriever.java:103)
	at com.intellij.util.indexing.impl.storage.VfsAwareMapReduceIndex.lambda$getFileIndexMetaData$3(VfsAwareMapReduceIndex.java:205)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:666)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:622)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$computeInNonCancelableSection$4(CoreProgressManager.java:234)
	at com.intellij.openapi.progress.Cancellation.computeInNonCancelableSection(Cancellation.java:99)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeInNonCancelableSection(CoreProgressManager.java:234)
	at com.intellij.util.indexing.impl.storage.VfsAwareMapReduceIndex.getFileIndexMetaData(VfsAwareMapReduceIndex.java:205)
	at com.intellij.util.indexing.impl.storage.VfsAwareMapReduceIndex.getFileIndexMetaData(VfsAwareMapReduceIndex.java:40)
	at com.intellij.indexing.composite.CompositeInvertedIndexBase.getFileIndexMetaData(CompositeInvertedIndexBase.java:170)
	at com.intellij.util.indexing.FileBasedIndexImpl.createSingleIndexValueApplier(FileBasedIndexImpl.java:1606)
	at com.intellij.util.indexing.FileBasedIndexImpl.lambda$doIndexFileContent$25(FileBasedIndexImpl.java:1473)
	at com.intellij.openapi.fileTypes.impl.FileTypeManagerImpl.freezeFileTypeTemporarilyWithProvidedValueIn(FileTypeManagerImpl.java:670)
	at com.intellij.util.indexing.FileBasedIndexImpl.doIndexFileContent(FileBasedIndexImpl.java:1421)
	at com.intellij.util.indexing.FileBasedIndexImpl.indexFileContent(FileBasedIndexImpl.java:1394)
	at com.intellij.util.indexing.FileBasedIndexImpl.processRefreshedFile(FileBasedIndexImpl.java:1342)
	at com.intellij.util.indexing.FileBasedIndexImpl$VirtualFileUpdateTask.doProcess(FileBasedIndexImpl.java:1743)
	at com.intellij.util.indexing.FileBasedIndexImpl$VirtualFileUpdateTask.doProcess(FileBasedIndexImpl.java:1740)
	at com.intellij.util.indexing.UpdateTask.process(UpdateTask.java:63)
	at com.intellij.util.indexing.UpdateTask.processAll(UpdateTask.java:32)
	at com.intellij.util.indexing.FileBasedIndexImpl.forceUpdate(FileBasedIndexImpl.java:1760)
	at com.intellij.util.indexing.FileBasedIndexImpl.ensureUpToDate(FileBasedIndexImpl.java:808)
	at com.intellij.psi.stubs.StubIndexEx.getContainingIds(StubIndexEx.java:390)
	at com.intellij.psi.stubs.StubIndexEx.processElements(StubIndexEx.java:167)
	at com.intellij.psi.stubs.StubIndex.getElements(StubIndex.java:103)
	at com.intellij.psi.stubs.StubIndex.getElements(StubIndex.java:91)
	at com.jetbrains.php.PhpIndexImpl.getElements(PhpIndexImpl.java:639)
	at com.jetbrains.php.PhpIndexImpl.getByName(PhpIndexImpl.java:1076)
	at com.jetbrains.php.PhpIndexImpl.getByFQN(PhpIndexImpl.java:1053)
	at com.jetbrains.php.PhpIndexImpl.getByFqnCacheAware(PhpIndexImpl.java:1134)
	at com.jetbrains.php.PhpIndexImpl.getClassesByFQNInternal(PhpIndexImpl.java:1129)
	at com.jetbrains.php.PhpIndexImpl.getAnyByFQN(PhpIndexImpl.java:1168)
	at com.magento.idea.magento2plugin.reference.provider.PhpClassReferenceProvider.getReferencesByElement(PhpClassReferenceProvider.java:80)
	at com.magento.idea.magento2plugin.reference.provider.CompositeReferenceProvider.getReferencesByElement(CompositeReferenceProvider.java:30)
	at com.intellij.psi.impl.source.resolve.reference.ReferenceProvidersRegistryImpl.getReferences(ReferenceProvidersRegistryImpl.java:182)
	at com.intellij.psi.impl.source.resolve.reference.ReferenceProvidersRegistryImpl.mapNotEmptyReferencesFromProviders(ReferenceProvidersRegistryImpl.java:163)
	at com.intellij.psi.impl.source.resolve.reference.ReferenceProvidersRegistryImpl.doGetReferencesFromProviders(ReferenceProvidersRegistryImpl.java:142)
	at com.intellij.psi.impl.source.resolve.reference.ReferenceProvidersRegistry.getReferencesFromProviders(ReferenceProvidersRegistry.java:43)
	at com.intellij.psi.impl.source.xml.XmlTokenImpl.getReferences(XmlTokenImpl.java:63)
	at com.intellij.psi.impl.SharedPsiElementImplUtil.addReferences(SharedPsiElementImplUtil.java:57)
	at com.intellij.psi.impl.SharedPsiElementImplUtil.findReferenceAt(SharedPsiElementImplUtil.java:33)
	at com.intellij.psi.impl.SharedPsiElementImplUtil.findReferenceAt(SharedPsiElementImplUtil.java:51)
	at com.intellij.psi.impl.source.tree.CompositePsiElement.findReferenceAt(CompositePsiElement.java:103)
	at com.intellij.psi.AbstractFileViewProvider.findReferenceAt(AbstractFileViewProvider.java:238)
	at com.intellij.psi.SingleRootFileViewProvider.findReferenceAt(SingleRootFileViewProvider.java:228)
	at com.intellij.psi.impl.source.PsiFileImpl.findReferenceAt(PsiFileImpl.java:531)
	at com.intellij.codeInsight.TargetElementUtilBase.findReference(TargetElementUtilBase.java:195)
	at com.intellij.codeInsight.TargetElementUtil.findReference(TargetElementUtil.java:93)
	at com.intellij.model.psi.impl.TargetsKt.fromTargetEvaluator(targets.kt:165)
	at com.intellij.model.psi.impl.TargetsKt.declarationsOrReferences(targets.kt:134)
	at com.intellij.model.psi.impl.TargetsKt.declaredReferencedData(targets.kt:41)
	at com.intellij.model.psi.impl.TargetsKt.targetSymbols(targets.kt:23)
	at com.intellij.lang.documentation.symbol.impl.DefaultTargetSymbolDocum
```

**To Reproduce** (*)

**Expected behavior** (*)

**Screenshots**

**Please complete the following information:** (*)

 - OS: Linux 5.15.0-56-generic
 - PhpStorm/Intellij version: 2022.3
 - Plugin Version: 4.4.0

**Additional context**

**Comment by VitaliyBoyko** [comment]
It seems the IDE build-cache was corrupted. Please try to remove the system directory when the IDE is closed. (https://www.jetbrains.com/help/idea/tuning-the-ide.html#system-directory)

https://intellij-support.jetbrains.com/hc/en-us/community/posts/4417602192658-PersistentEnumeratorBase-CorruptedException
