### ISSUE TITLE
PhpStorm 2023.1 issue

### ISSUE THREAD

**Issue by an2riy** [magento/magento2-phpstorm-plugin#1346]
**Describe the bug**

```
com.intellij.diagnostic.PluginException: Cannot create class com.magento.idea.magento2plugin.actions.groups.NewModuleFileGroup (classloader=PluginClassLoader(plugin=PluginDescriptor(name=Magento PhpStorm, id=com.magento.idea.magento2plugin, descriptorPath=plugin.xml, path=~/.local/share/JetBrains/PhpStorm2023.1/com.magento.idea.magento2plugin, version=5.0.1, package=null, isBundled=false), packagePrefix=null, instanceId=160, state=active))
	at com.intellij.serviceContainer.ComponentManagerImpl.instantiateClass(ComponentManagerImpl.kt:1034)
	at com.intellij.serviceContainer.ComponentManagerImpl.instantiateClass(ComponentManagerImpl.kt:1051)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.instantiate(ActionManagerImpl.java:200)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.convertGroupStub(ActionManagerImpl.java:240)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.getActionImpl(ActionManagerImpl.java:542)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.getAction(ActionManagerImpl.java:531)
	at com.intellij.openapi.actionSystem.DefaultActionGroup.unStub(DefaultActionGroup.java:401)
	at com.intellij.openapi.actionSystem.DefaultActionGroup.getChildren(DefaultActionGroup.java:357)
	at com.intellij.openapi.actionSystem.DefaultActionGroup.getChildren(DefaultActionGroup.java:336)
	at com.intellij.ide.actions.WeighingActionGroup.getChildren(WeighingActionGroup.java:44)
	at com.intellij.ide.actions.WeighingNewActionGroup.getChildren(WeighingNewActionGroup.java:25)
	at com.intellij.openapi.keymap.impl.ui.ActionsTreeUtil.getActions(ActionsTreeUtil.java:745)
	at com.intellij.openapi.keymap.impl.ui.ActionsTreeUtil.createGroup(ActionsTreeUtil.java:233)
	at com.intellij.openapi.keymap.impl.ui.ActionsTreeUtil.createGroup(ActionsTreeUtil.java:241)
	at com.intellij.openapi.keymap.impl.ui.ActionsTreeUtil.createGroup(ActionsTreeUtil.java:221)
	at com.intellij.openapi.keymap.impl.ui.ActionsTreeUtil.createGroup(ActionsTreeUtil.java:187)
	at com.intellij.ide.ui.customization.ActionUrl.readExternal(ActionUrl.java:134)
	at com.intellij.ide.ui.customization.CustomActionsSchema.loadState(CustomActionsSchema.kt:232)
	at com.intellij.ide.ui.customization.CustomActionsSchema.loadState(CustomActionsSchema.kt:51)
	at com.intellij.configurationStore.ComponentStoreImpl.doInitComponent(ComponentStoreImpl.kt:435)
	at com.intellij.configurationStore.ComponentStoreImpl.initComponent(ComponentStoreImpl.kt:368)
	at com.intellij.configurationStore.ComponentStoreImpl.initComponent(ComponentStoreImpl.kt:119)
	at com.intellij.configurationStore.ComponentStoreWithExtraComponents.initComponent(ComponentStoreWithExtraComponents.kt:46)
	at com.intellij.serviceContainer.ComponentManagerImpl.initializeComponent$intellij_platform_serviceContainer(ComponentManagerImpl.kt:622)
	at com.intellij.serviceContainer.ServiceComponentAdapter.createAndInitialize(ServiceComponentAdapter.kt:47)
	at com.intellij.serviceContainer.ServiceComponentAdapter.doCreateInstance(ServiceComponentAdapter.kt:39)
	at com.intellij.serviceContainer.BaseComponentAdapter.doCreateInstance(BaseComponentAdapter.kt:154)
	at com.intellij.serviceContainer.BaseComponentAdapter.createInstance$lambda$1(BaseComponentAdapter.kt:133)
	at com.intellij.openapi.progress.Cancellation.computeInNonCancelableSection(Cancellation.java:99)
	at com.intellij.serviceContainer.BaseComponentAdapter.createInstance(BaseComponentAdapter.kt:132)
	at com.intellij.serviceContainer.BaseComponentAdapter.access$createInstance(BaseComponentAdapter.kt:19)
	at com.intellij.serviceContainer.BaseComponentAdapter$getInstanceAsync$2.invokeSuspend(BaseComponentAdapter.kt:181)
	at com.intellij.serviceContainer.BaseComponentAdapter$getInstanceAsync$2.invoke(BaseComponentAdapter.kt)
	at com.intellij.serviceContainer.BaseComponentAdapter$getInstanceAsync$2.invoke(BaseComponentAdapter.kt)
	at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:89)
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Builders.common.kt:169)
	at kotlinx.coroutines.BuildersKt.withContext(Unknown Source)
	at com.intellij.serviceContainer.BaseComponentAdapter.getInstanceAsync(BaseComponentAdapter.kt:176)
	at com.intellij.serviceContainer.ComponentManagerImpl.getServiceAsyncIfDefined(ComponentManagerImpl.kt:686)
	at com.intellij.serviceContainer.ComponentManagerImpl.getServiceAsync(ComponentManagerImpl.kt:677)
	at com.intellij.openapi.wm.impl.headertoolbar.MainToolbar$Companion.computeActionGroups(MainToolbar.kt:50)
	at com.intellij.openapi.project.impl.ProjectUiFrameAllocator$run$2$deferredToolbarActionGroups$1.invokeSuspend(ProjectFrameAllocator.kt:127)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
Caused by: com.intellij.diagnostic.PluginException: Cannot load class com.magento.idea.magento2plugin.actions.groups.NewModuleFileGroup$1 (
  error: com/intellij/openapi/util/IconLoader$LazyIcon,
  classLoader=PluginClassLoader(plugin=PluginDescriptor(name=Magento PhpStorm, id=com.magento.idea.magento2plugin, descriptorPath=plugin.xml, path=~/.local/share/JetBrains/PhpStorm2023.1/com.magento.idea.magento2plugin, version=5.0.1, package=null, isBundled=false), packagePrefix=null, instanceId=160, state=active)
)
	at com.intellij.ide.plugins.cl.PluginClassLoader.loadClassInsideSelf(PluginClassLoader.kt:325)
	at com.intellij.ide.plugins.cl.PluginClassLoader.tryLoadingClass(PluginClassLoader.kt:172)
	at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.kt:145)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at com.magento.idea.magento2plugin.actions.groups.NewModuleFileGroup.<init>(NewModuleFileGroup.java:32)
	at com.intellij.serviceContainer.ComponentManagerImpl.instantiateClass(ComponentManagerImpl.kt:993)
	... 47 more
Caused by: java.lang.NoClassDefFoundError: com/intellij/openapi/util/Ico
```

**To Reproduce** (*)

After open a project.

**Please complete the following information:** (*)

 - OS: Linux 5.15.0-69-generic
 - PhpStorm/Intellij version: 2023.1
 - Plugin Version: 5.0.1

**Additional context**

PhpStorm 2023.1
Build #PS-231.8109.199, built on March 30, 2023
Runtime version: 17.0.6+10-b829.5 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Linux 5.15.0-69-generic
GC: G1 Young Generation, G1 Old Generation
Memory: 5120M
Cores: 12
Registry:
    editor.focus.mode.color.light=5b595c
    ide.editor.tab.selection.animation=true
    debugger.watches.in.variables=false
    debugger.new.tool.window.layout=true
    editor.caret.width=1
    run.processes.with.pty=true
    vcs.new.widget=true
    ide.new.editor.tabs.vertical.borders=true
    ide.experimental.ui=true
    ide.balloon.shadow.size=0
    editor.focus.mode.color.dark=5b595c

Non-Bundled Plugins:
    de.femtopedia.diffplugin (2.1.10)
    intellij-awk (0.3.10)
    org.toml.lang (231.8109.91)
    com.ultrahob.zerolength.plugin (0.95)
    org.elasticsearch4idea (2023.1.4-231)
    com.intellij.properties (231.8109.91)
    String Manipulation (9.7.1)
    ir.msdehghan.plugins.ansible (0.92)
    com.alayouni.ansiHighlight (23.1.0)
    indent-rainbow.indent-rainbow (2.1.0)
    com.intellij.grazie.pro (0.3.214)
    com.kalessil.phpStorm.phpInspectionsEA (4.0.7.1)
    ru.adelf.idea.dotenv (2023.1)
    de.espend.idea.php.annotation (9.2.0)
    com.virtuslab.git-machete (3.8.0)
    izhangzhihao.rainbow.brackets (2023.2.6)
    pro.bashsupport (3.2.1.231)
    lv.midiana.misc.phpstorm-plugins.deep-keys (2022.08.03.001)
    fr.adrienbrault.idea.symfony2plugin (2022.1.246)
    com.chrisrm.idea.MaterialThemeUI (8.6.0)
    com.intellij.lang.jsgraphql (3.4.0)
    com.magento.idea.magento2plugin (5.0.1)
    uk.co.ben-gibson.remote.repository.mapper (4.3.2)
    org.sonarlint.idea (8.1.0.65508)
    com.mallowigi (90.0.0)
    zielu.gittoolbox (500.0.5+213)
    mobi.hsz.idea.gitignore (4.5.0)
    com.github.blarc.gitlab-template-lint-plugin (1.6.0)

Current Desktop: ubuntu:GNOME

**Comment by an2riy** [comment]
@magento I am working on this

**Comment by VitaliyBoyko** [comment]
fixed in #1214
Released in 5.1.0

**Comment by an2riy** [comment]
@VitaliyBoyko do you know when it will be published? Because each time I re-open a PHPStorm a project is indexed because of the issue.

**Comment by VitaliyBoyko** [comment]
1-2 days

Please temporary remove the plugin or downgrade the phpstorm
