### ISSUE TITLE
com.intellij.util.io.PersistentEnumeratorBase$CorruptedException: PersistentEnumerator storage corrupted /home/sautushka/.cache/JetBrains/PhpStorm2023.1/index/stubs/.perFileVersion/indexed_versions/indexed_versions

### ISSUE THREAD

**Issue by SAutushka** [magento/magento2-phpstorm-plugin#1510]
**Describe the bug** (*)

```
com.intellij.util.io.PersistentEnumeratorBase$CorruptedException: PersistentEnumerator storage corrupted /home/sautushka/.cache/JetBrains/PhpStorm2023.1/index/stubs/.perFileVersion/indexed_versions/indexed_versions
	at com.intellij.util.io.PersistentEnumeratorBase.catchCorruption(PersistentEnumeratorBase.java:615)
	at com.intellij.util.io.PersistentEnumeratorBase.valueOf(PersistentEnumeratorBase.java:426)
	at com.intellij.util.io.PersistentBTreeEnumerator.valueOf(PersistentBTreeEnumerator.java:733)
	at com.intellij.util.io.PersistentEnumeratorBase$1.process(PersistentEnumeratorBase.java:324)
	at com.intellij.util.io.PersistentBTreeEnumerator$3.process(PersistentBTreeEnumerator.java:383)
	at com.intellij.util.io.IntToIntBtree$BtreeIndexNodeView.lambda$processMappings$1(IntToIntBtree.java:629)
	at com.intellij.util.io.IntToIntBtree$BtreeIndexNodeView.processMappings(IntToIntBtree.java:632)
	at com.intellij.util.io.IntToIntBtree.processLeafPages(IntToIntBtree.java:1045)
	at com.intellij.util.io.IntToIntBtree.processMappings(IntToIntBtree.java:1040)
	at com.intellij.util.io.PersistentBTreeEnumerator.traverseAllRecords(PersistentBTreeEnumerator.java:372)
	at com.intellij.util.io.PersistentEnumeratorBase.processAllDataObject(PersistentEnumeratorBase.java:320)
	at com.intellij.util.io.PersistentBTreeEnumerator.processAllDataObject(PersistentBTreeEnumerator.java:363)
	at com.intellij.util.io.PersistentMapImpl.processExistingKeys(PersistentMapImpl.java:590)
	at com.intellij.util.io.PersistentHashMap.processKeysWithExistingMapping(PersistentHashMap.java:192)
	at com.intellij.util.indexing.impl.perFileVersion.PersistentSubIndexerVersionEnumerator.valueOf(PersistentSubIndexerVersionEnumerator.java:85)
	at com.intellij.util.indexing.impl.perFileVersion.PersistentSubIndexerRetriever.getVersionByIndexerId(PersistentSubIndexerRetriever.java:117)
	at com.intellij.util.indexing.impl.storage.VfsAwareMapReduceIndex.getStoredSubIndexerVersion(VfsAwareMapReduceIndex.java:235)
	at com.intellij.psi.stubs.PerFileElementTypeStubModificationTracker.determinePreviousFileElementType(PerFileElementTypeStubModificationTracker.java:197)
	at com.intellij.psi.stubs.PerFileElementTypeStubModificationTracker.fastCheck(PerFileElementTypeStubModificationTracker.java:101)
	at com.intellij.psi.stubs.PerFileElementTypeStubModificationTracker.lambda$endUpdatesBatch$2(PerFileElementTypeStubModificationTracker.java:76)
	at com.intellij.openapi.application.ReadAction.lambda$run$1(ReadAction.java:60)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:891)
	at com.intellij.openapi.application.ReadAction.compute(ReadAction.java:69)
	at com.intellij.openapi.application.ReadAction.run(ReadAction.java:59)
	at com.intellij.psi.stubs.PerFileElementTypeStubModificationTracker.endUpdatesBatch(PerFileElementTypeStubModificationTracker.java:75)
	at com.intellij.util.indexing.events.ChangedFilesCollector$4.endBatch(ChangedFilesCollector.java:246)
	at com.intellij.util.indexing.events.ChangedFilesCollector$5.lambda$endBatch$2(ChangedFilesCollector.java:283)
	at com.intellij.util.ConcurrencyUtil.withLock(ConcurrencyUtil.java:258)
	at com.intellij.util.indexing.events.ChangedFilesCollector$5.endBatch(ChangedFilesCollector.java:282)
	at com.intellij.util.indexing.events.VfsEventsMerger.processChanges(VfsEventsMerger.java:109)
	at com.intellij.util.indexing.events.ChangedFilesCollector.processFilesInReadAction(ChangedFilesCollector.java:265)
	at com.intellij.util.indexing.events.ChangedFilesCollector.processFilesToUpdateInReadAction(ChangedFilesCollector.java:224)
	at com.intellij.util.indexing.events.ChangedFilesCollector.ensureUpToDate(ChangedFilesCollector.java:190)
	at com.intellij.util.indexing.FileBasedIndexImpl.ensureUpToDate(FileBasedIndexImpl.java:836)
	at com.intellij.psi.stubs.StubIndexEx.getContainingIds(StubIndexEx.java:365)
	at com.intellij.psi.stubs.StubIndexEx.processElements(StubIndexEx.java:166)
	at com.intellij.psi.stubs.StubIndex.getElements(StubIndex.java:102)
	at com.intellij.psi.stubs.StubIndex.getElements(StubIndex.java:90)
	at com.jetbrains.php.PhpIndexImpl.getElements(PhpIndexImpl.java:739)
	at com.jetbrains.php.PhpIndexImpl.getByName(PhpIndexImpl.java:1176)
	at com.jetbrains.php.PhpIndexImpl.getByFQN(PhpIndexImpl.java:1153)
	at com.jetbrains.php.PhpIndexImpl.getByFqnCacheAware(PhpIndexImpl.java:1234)
	at com.jetbrains.php.PhpIndexImpl.getClassesByFQNInternal(PhpIndexImpl.java:1229)
	at com.jetbrains.php.PhpIndexImpl.getAnyByFQN(PhpIndexImpl.java:1268)
	at com.magento.idea.magento2plugin.reference.provider.PhpClassReferenceProvider.getReferencesByElement(PhpClassReferenceProvider.java:80)
	at com.magento.idea.magento2plugin.reference.provider.CompositeReferenceProvider.getReferencesByElement(CompositeReferenceProvider.java:30)
	at com.intellij.psi.impl.source.resolve.reference.ReferenceProvidersRegistryImpl.getReferences(ReferenceProvidersRegistryImpl.java:182)
	at com.intellij.psi.impl.source.resolve.reference.ReferenceProvidersRegistryImpl.mapNotEmptyReferencesFromProviders(ReferenceProvidersRegistryImpl.java:163)
	at com.intellij.psi.impl.source.resolve.reference.ReferenceProvidersRegistryImpl.doGetReferencesFromProviders(ReferenceProvidersRegistryImpl.java:142)
	at com.intellij.psi.impl.source.resolve.reference.ReferenceProvidersRegistry.getReferencesFromProviders(ReferenceProvidersRegistry.java:43)
	at com.intellij.psi.impl.source.xml.XmlAttributeValueImpl.getReferences(XmlAttributeValueImpl.java:80)
	at com.intellij.psi.impl.SharedPsiElementImplUtil.addReferences(SharedPsiElementImplUtil.java:58)
	at com.intellij.psi.impl.SharedPsiElementImplUtil.findReferenceAt(SharedPsiElementImplUtil.java:34)
	at com.intellij.psi.impl.SharedPsiElementImplUtil.findReferenceAt(SharedPsiElementImplUtil.java:52)
	at com.intellij.psi.impl.source.tree.CompositePsiElement.findReferenceAt(CompositePsiElement.java:103)
	at com.intellij.psi.AbstractFileViewProvider.findReferenceAt(AbstractFileViewProvider.java:234)
	at com.intellij.psi.SingleRootFileViewProvider.findReferenceAt(SingleRootFileViewProvider.java:228)
	at com.intellij.psi.impl.source.PsiFileImpl.findReferenceAt(PsiFileImpl.java:531)
	at com.intellij.codeInsight.TargetElementUtilBase.findReference(TargetElementUtilBase.java:194)
	at com.intellij.sql.SqlHighlightAsteriskFactory.createHighlightUsagesHandler(SqlHighlightAsteriskFactory.kt:20)
	at com.intellij.codeInsight.highlighting.HighlightUsage
```

**To Reproduce** (*)

**Expected behavior** (*)

**Screenshots**

**Please complete the following information:** (*)

 - OS: Linux 6.2.9-200.fc37.x86_64
 - PhpStorm/Intellij version: 2023.1
 - Plugin Version: 5.1.0

**Additional context**

**Comment by VitaliyBoyko** [comment]
It seems the IDE build-cache was corrupted. Please try to remove the system directory when the IDE is closed. (https://www.jetbrains.com/help/idea/tuning-the-ide.html#system-directory)

https://intellij-support.jetbrains.com/hc/en-us/community/posts/4417602192658-PersistentEnumeratorBase-CorruptedException
