### ISSUE TITLE
Bug Report 2023/11/11

### ISSUE THREAD

**Issue by agustinamartinez1044** [magento/magento2-phpstorm-plugin#1789]
**Describe the bug** (*)

```
com.intellij.diagnostic.PluginException: Cannot create class com.magento.idea.magento2plugin.actions.groups.NewModuleFileGroup (classloader=PluginClassLoader(plugin=PluginDescriptor(name=Magento PhpStorm, id=com.magento.idea.magento2plugin, descriptorPath=plugin.xml, path=~\AppData\Roaming\JetBrains\IntelliJIdea2023.2\plugins\com.magento.idea.magento2plugin, version=5.0.1, package=null, isBundled=false), packagePrefix=null, state=active))
	at com.intellij.serviceContainer.ComponentManagerImpl.doInstantiateClass(ComponentManagerImpl.kt:1003)
	at com.intellij.serviceContainer.ComponentManagerImpl.instantiateClass(ComponentManagerImpl.kt:954)
	at com.intellij.serviceContainer.ComponentManagerImpl.instantiateClass(ComponentManagerImpl.kt:1022)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImplKt.instantiate(ActionManagerImpl.kt:1416)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImplKt.convertGroupStub(ActionManagerImpl.kt:1459)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImplKt.access$convertGroupStub(ActionManagerImpl.kt:1)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.getActionImpl(ActionManagerImpl.kt:314)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.getAction(ActionManagerImpl.kt:302)
	at com.intellij.openapi.actionSystem.DefaultActionGroup.getChildren(DefaultActionGroup.java:357)
	at com.intellij.openapi.actionSystem.DefaultActionGroup.getChildren(DefaultActionGroup.java:334)
	at com.intellij.ide.actions.WeighingActionGroup.getChildren(WeighingActionGroup.java:44)
	at com.intellij.ide.actions.WeighingNewActionGroup.getChildren(WeighingNewActionGroup.java:11)
	at com.intellij.openapi.keymap.impl.ui.ActionsTreeUtil.getActions(ActionsTreeUtil.java:741)
	at com.intellij.openapi.keymap.impl.ui.ActionsTreeUtil.createGroup(ActionsTreeUtil.java:231)
	at com.intellij.openapi.keymap.impl.ui.ActionsTreeUtil.createGroup(ActionsTreeUtil.java:239)
	at com.intellij.openapi.keymap.impl.ui.ActionsTreeUtil.createGroup(ActionsTreeUtil.java:219)
	at com.intellij.openapi.keymap.impl.ui.ActionsTreeUtil.createGroup(ActionsTreeUtil.java:186)
	at com.intellij.ide.ui.customization.ActionUrl.readExternal(ActionUrl.java:134)
	at com.intellij.ide.ui.customization.CustomActionsSchema.loadState(CustomActionsSchema.kt:234)
	at com.intellij.ide.ui.customization.CustomActionsSchema.loadState(CustomActionsSchema.kt:58)
	at com.intellij.configurationStore.ComponentStoreImpl.doInitComponent(ComponentStoreImpl.kt:488)
	at com.intellij.configurationStore.ComponentStoreImpl.initComponent(ComponentStoreImpl.kt:415)
	at com.intellij.configurationStore.ComponentStoreImpl.initComponent(ComponentStoreImpl.kt:121)
	at com.intellij.configurationStore.ComponentStoreWithExtraComponents.initComponent(ComponentStoreWithExtraComponents.kt:48)
	at com.intellij.serviceContainer.ComponentManagerImpl.initializeComponent$intellij_platform_serviceContainer(ComponentManagerImpl.kt:577)
	at com.intellij.serviceContainer.ServiceComponentAdapter.createAndInitialize(ServiceComponentAdapter.kt:51)
	at com.intellij.serviceContainer.ServiceComponentAdapter.doCreateInstance(ServiceComponentAdapter.kt:43)
	at com.intellij.serviceContainer.BaseComponentAdapter.doCreateInstance(BaseComponentAdapter.kt:158)
	at com.intellij.serviceContainer.BaseComponentAdapter.createInstance(BaseComponentAdapter.kt:137)
	at com.intellij.serviceContainer.BaseComponentAdapter.access$createInstance(BaseComponentAdapter.kt:21)
	at com.intellij.serviceContainer.BaseComponentAdapter$getInstanceAsync$2.invokeSuspend(BaseComponentAdapter.kt:185)
	at com.intellij.serviceContainer.BaseComponentAdapter$getInstanceAsync$2.invoke(BaseComponentAdapter.kt)
	at com.intellij.serviceContainer.BaseComponentAdapter$getInstanceAsync$2.invoke(BaseComponentAdapter.kt)
	at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:78)
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Builders.common.kt:167)
	at kotlinx.coroutines.BuildersKt.withContext(Unknown Source)
	at com.intellij.serviceContainer.BaseComponentAdapter.getInstanceAsync(BaseComponentAdapter.kt:180)
	at com.intellij.serviceContainer.ComponentManagerImpl.getServiceAsyncIfDefined(ComponentManagerImpl.kt:646)
	at com.intellij.serviceContainer.ComponentManagerImpl.getServiceAsync(ComponentManagerImpl.kt:637)
	at com.intellij.ide.bootstrap.AppServicePreloadingKt$preloadCriticalServices$2$4.invokeSuspend(appServicePreloading.kt:179)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)
Caused by: com.intellij.diagnostic.PluginException: Cannot load class com.magento.idea.magento2plugin.actions.groups.NewModuleFileGroup$1 (
  error: com/intellij/openapi/util/IconLoader$LazyIcon,
  classLoader=PluginClassLoader(plugin=PluginDescriptor(name=Magento PhpStorm, id=com.magento.idea.magento2plugin, descriptorPath=plugin.xml, path=~\AppData\Roaming\JetBrains\IntelliJIdea2023.2\plugins\com.magento.idea.magento2plugin, version=5.0.1, package=null, isBundled=false), packagePrefix=null, state=active)
)
	at com.intellij.ide.plugins.cl.PluginClassLoader.loadClassInsideSelf(PluginClassLoader.kt:331)
	at com.intellij.ide.plugins.cl.PluginClassLoader.tryLoadingClass(PluginClassLoader.kt:178)
	at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.kt:151)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
	at com.magento.idea.magento2plugin.actions.groups.NewModuleFileGroup.<init>(NewModuleFileGroup.java:32)
	at com.intellij.serviceContainer.ComponentManagerImpl.doInstantiateClass(ComponentManagerImpl.kt:962)
	... 45 more
Caused by: java.lang.NoClassDefFoundError: com/intellij/openapi/util/IconLoader$LazyIcon
	at java.base/java.lang.ClassLoader.defineClass2(Native Met
```

**To Reproduce** (*)

**Expected behavior** (*)

**Screenshots**

**Please complete the following information:** (*)

 - OS: Windows 10.0
 - PhpStorm/Intellij version: 2023.2.5
 - Plugin Version: 5.0.1

**Additional context**

**Comment by VitaliyBoyko** [comment]
fixed in #1214
since 5.1.0
