### ISSUE TITLE
Bug Report 2023/12/19

### ISSUE THREAD

**Issue by JhonatanValero** [magento/magento2-phpstorm-plugin#1843]
**Describe the bug** (*)

```
com.intellij.diagnostic.PluginException: 2593 ms to call on EDT CreateAPluginAction#Update@EditorPopup (com.magento.idea.magento2plugin.actions.generation.CreateAPluginAction). Revise AnAction.getActionUpdateThread property [Plugin: com.magento.idea.magento2plugin]
	at com.intellij.diagnostic.PluginProblemReporterImpl.createPluginExceptionByClass(PluginProblemReporterImpl.java:23)
	at com.intellij.diagnostic.PluginException.createByClass(PluginException.java:89)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.computeOnEdt(ActionUpdater.kt:223)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.access$computeOnEdt(ActionUpdater.kt:71)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater$computeOnEdt$1.invokeSuspend(ActionUpdater.kt)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
	at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:115)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:103)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)
	Suppressed: java.lang.Throwable: EDT-trace-at-398-ms (5/5)
		at java.base@17.0.9/jdk.internal.misc.Unsafe.park(Native Method)
		at java.base@17.0.9/java.util.concurrent.locks.LockSupport.park(LockSupport.java:211)
		at java.base@17.0.9/java.util.concurrent.locks.AbstractQueuedSynchronizer.acquire(AbstractQueuedSynchronizer.java:715)
		at java.base@17.0.9/java.util.concurrent.locks.AbstractQueuedSynchronizer.acquire(AbstractQueuedSynchronizer.java:938)
		at java.base@17.0.9/java.util.concurrent.locks.ReentrantReadWriteLock$WriteLock.lock(ReentrantReadWriteLock.java:959)
		at com.intellij.util.ConcurrencyUtil.withLock(ConcurrencyUtil.java:244)
		at com.intellij.util.indexing.events.ChangedFilesCollector$5.process(ChangedFilesCollector.java:281)
		at com.intellij.util.indexing.events.VfsEventsMerger.processChanges(VfsEventsMerger.java:101)
		at com.intellij.util.indexing.events.ChangedFilesCollector.processFilesInReadAction(ChangedFilesCollector.java:278)
		at com.intellij.util.indexing.events.ChangedFilesCollector.processFilesToUpdateInReadAction(ChangedFilesCollector.java:230)
		at com.intellij.util.indexing.events.ChangedFilesCollector.ensureUpToDate(ChangedFilesCollector.java:191)
		at com.intellij.util.indexing.FileBasedIndexImpl.ensureUpToDate(FileBasedIndexImpl.java:747)
		at com.intellij.psi.stubs.StubIndexEx.getContainingIds(StubIndexEx.java:357)
		at com.intellij.psi.stubs.StubIndexEx.processElements(StubIndexEx.java:167)
		at com.intellij.psi.stubs.StubIndex.getElements(StubIndex.java:102)
		at com.intellij.psi.stubs.StubIndex.getElements(StubIndex.java:90)
		at com.jetbrains.php.PhpIndexImpl.getElements(PhpIndexImpl.java:746)
		at com.jetbrains.php.PhpIndexImpl.getByName(PhpIndexImpl.java:1183)
		at com.jetbrains.php.PhpIndexImpl.getByFQN(PhpIndexImpl.java:1160)
		at com.jetbrains.php.PhpIndexImpl.getByFqnCacheAware(PhpIndexImpl.java:1241)
		at com.jetbrains.php.PhpIndexImpl.getClassesByFQNInternal(PhpIndexImpl.java:1236)
		at com.jetbrains.php.PhpIndexImpl.getInterfacesByFQN(PhpIndexImpl.java:1261)
		at com.jetbrains.php.lang.psi.elements.PhpClass.getDirectImplementedInterfaces(PhpClass.java:87)
		at com.jetbrains.php.lang.psi.elements.impl.PhpClassImpl.getImplementedInterfaces(PhpClassImpl.java:571)
		at com.magento.idea.magento2plugin.inspections.php.util.PhpClassImplementsNoninterceptableInterfaceUtil$$Lambda$11236/0x000000010262f990.compute(Unknown Source)
		at com.intellij.util.SlowOperations.allowSlowOperations(SlowOperations.java:195)
		at com.magento.idea.magento2plugin.inspections.php.util.PhpClassImplementsNoninterceptableInterfaceUtil.execute(PhpClassImplementsNoninterceptableInterfaceUtil.java:25)
		at com.magento.idea.magento2plugin.actions.generation.CreateAPluginAction.update(CreateAPluginAction.java:60)
		at com.intellij.openapi.actionSystem.ex.ActionUtil.lambda$performDumbAwareUpdate$0(ActionUtil.java:164)
		at com.intellij.openapi.actionSystem.ex.ActionUtil$$Lambda$1289/0x0000000100bf5650.run(Unknown Source)
		at com.intellij.openapi.actionSystem.ex.ActionUtil.performDumbAwareUpdate(ActionUtil.java:187)
		at com.intellij.openapi.actionSystem.impl.ActionUpdaterKt.doUpdate(ActionUpdater.kt:696)
		at com.intellij.openapi.actionSystem.impl.ActionUpdaterKt.access$doUpdate(ActionUpdater.kt:1)
		at com.intellij.openapi.actionSystem.impl.ActionUpdater$updateActionReal$success$1.invoke(ActionUpdater.kt:110)
		at com.intellij.openapi.actionSystem.impl.ActionUpdater$updateActionReal$success$1.invoke(ActionUpdater.kt:109)
		at com.intellij.openapi.actionSystem.impl.ActionUpdater$callAction$4.invoke(ActionUpdater.kt:178)
		at com.intellij.openapi.actionSystem.impl.ActionUpdater$computeOnEdt$2.invoke(ActionUpdater.kt:204)
		at com.intellij.openapi.actionSystem.impl.ActionUpdater$computeOnEdt$deferred$1$1.invoke(ActionUpdater.kt:468)
		at com.intellij.openapi.progress.CoroutinesKt.blockingContextInner(coroutines.kt:321)
		at com.intellij.openapi.progress.CoroutinesKt.access$blockingContextInner(coroutines.kt:1)
		at com.intellij.openapi.progress.CoroutinesKt$blockingContext$2.invokeSuspend(coroutines.kt:198)
		at com.intellij.openapi.progress.CoroutinesKt$blockingContext$2.invoke(coroutines.kt)
		at com.intellij.openapi.progress.CoroutinesKt$blockingContext$2.invoke(coroutines.kt)
		at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:78)
		at kotlinx.coroutines.CoroutineScopeKt.coroutineScope(CoroutineScope.kt:264)
		at com.intellij.openapi.progress.CoroutinesKt.blockingContext(coroutines.kt:197)
		at com.intellij.openapi.actionSystem.impl.ActionUpdater$computeOnEdt$deferred$1.invokeSuspend(ActionUpdater.kt:467)
		at kotlin.coroutines.jvm.internal.B
```

**To Reproduce** (*)

**Expected behavior** (*)

**Screenshots**

**Please complete the following information:** (*)

 - OS: Windows 11.0
 - PhpStorm/Intellij version: 2023.3
 - Plugin Version: 5.1.1

**Additional context**

**Comment by VitaliyBoyko** [comment]
Duplicate of https://github.com/magento/magento2-phpstorm-plugin/issues/1238

**Comment by JhonatanValero** [comment]
[celebrate]     Jhonatan Stiven Valero reacted to your message:
________________________________
