### ISSUE TITLE
java.lang.RuntimeException: com.intellij.util.io.CorruptedException: file

### ISSUE THREAD

**Issue by aganganna-usgb** [magento/magento2-phpstorm-plugin#1854]
**Describe the bug** (*)

```
java.lang.RuntimeException: com.intellij.util.io.CorruptedException: file[4553].child[0][#705386] is out of allocated id range (0..701194] -> VFS is corrupted (was IDE forcibly terminated?)
	at com.intellij.util.ExceptionUtil.rethrow(ExceptionUtil.java:138)
	at com.intellij.openapi.vfs.newvfs.persistent.FSRecordsImpl.lambda$static$0(FSRecordsImpl.java:96)
	at com.intellij.openapi.vfs.newvfs.persistent.FSRecordsImpl.handleError(FSRecordsImpl.java:1172)
	at com.intellij.openapi.vfs.newvfs.persistent.FSRecordsImpl.list(FSRecordsImpl.java:501)
	at com.intellij.openapi.vfs.newvfs.persistent.FSRecordsImpl.update(FSRecordsImpl.java:530)
	at com.intellij.openapi.vfs.newvfs.persistent.FSRecords.update(FSRecords.java:256)
	at com.intellij.openapi.vfs.newvfs.persistent.PersistentFSImpl.findChildInfo(PersistentFSImpl.java:509)
	at com.intellij.openapi.vfs.newvfs.impl.VirtualDirectoryImpl.findInPersistence(VirtualDirectoryImpl.java:154)
	at com.intellij.openapi.vfs.newvfs.impl.VirtualDirectoryImpl.doFindChild(VirtualDirectoryImpl.java:137)
	at com.intellij.openapi.vfs.newvfs.impl.VirtualDirectoryImpl.findChild(VirtualDirectoryImpl.java:83)
	at com.intellij.openapi.vfs.newvfs.impl.VirtualDirectoryImpl.findChild(VirtualDirectoryImpl.java:532)
	at com.intellij.openapi.vfs.newvfs.impl.VirtualDirectoryImpl.findChild(VirtualDirectoryImpl.java:51)
	at com.jetbrains.php.config.library.PhpRuntimeLibraryRootsProvider.lambda$getLibraryRootsBeforeFiltering$7(PhpRuntimeLibraryRootsProvider.java:96)
	at java.base/java.util.stream.ReferencePipeline$15$1.accept(ReferencePipeline.java:540)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
	at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:992)
	at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:762)
	at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:276)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.stream.Streams$StreamBuilderImpl.forEachRemaining(Streams.java:411)
	at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:762)
	at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:276)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
	at java.base/java.util.stream.ReferencePipeline$15$1.accept(ReferencePipeline.java:541)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.Iterator.forEachRemaining(Iterator.java:133)
	at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1845)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
	at one.util.streamex.AbstractStreamEx.rawCollect(AbstractStreamEx.java:109)
	at one.util.streamex.AbstractStreamEx.collect(AbstractStreamEx.java:519)
	at com.jetbrains.php.config.library.PhpRuntimeLibraryRootsProvider.getLibraryRootsBeforeFiltering(PhpRuntimeLibraryRootsProvider.java:97)
	at com.jetbrains.php.config.library.PhpRuntimeLibraryRootsProvider.getLibraryRootsInternal(PhpRuntimeLibraryRootsProvider.java:60)
	at com.jetbrains.php.config.library.PhpRuntimeLibraryRootsProvider.doGetRootsInternal(PhpRuntimeLibraryRootsProvider.java:124)
	at com.jetbrains.php.config.library.PhpRuntimeLibraryRootsProvider.lambda$getLibraryRoots$10(PhpRuntimeLibraryRootsProvider.java:118)
	at com.intellij.psi.impl.PsiCachedValueImpl.doCompute(PsiCachedValueImpl.java:37)
	at com.intellij.util.CachedValueBase.lambda$getValueWithLock$3(CachedValueBase.java:240)
	at com.intellij.util.CachedValueBase.computeData(CachedValueBase.java:43)
	at com.intellij.util.CachedValueBase.lambda$getValueWithLock$4(CachedValueBase.java:240)
	at com.intellij.openapi.util.RecursionManager$1.computePreventingRecursion(RecursionManager.java:110)
	at com.intellij.openapi.util.RecursionGuard.doPreventingRecursion(RecursionGuard.java:27)
	at com.intellij.openapi.util.RecursionManager.doPreventingRecursion(RecursionManager.java:65)
	at com.intellij.util.CachedValueBase.getValueWithLock(CachedValueBase.java:241)
	at com.intellij.psi.impl.PsiCachedValueImpl.getValue(PsiCachedValueImpl.java:27)
	at com.intellij.util.CachedValuesManagerImpl.getCachedValue(CachedValuesManagerImpl.java:69)
	at com.intellij.psi.util.CachedValuesManager.getCachedValue(CachedValuesManager.java:111)
	at com.jetbrains.php.config.library.PhpRuntimeLibraryRootsProvider.getLibraryRoots(PhpRuntimeLibraryRootsProvider.java:119)
	at com.jetbrains.php.PhpProjectScopeBuilder$1.contains(PhpProjectScopeBuilder.java:29)
	at com.intellij.psi.search.DelegatingGlobalSearchScope.contains(DelegatingGlobalSearchScope.java:46)
	at com.intellij.psi.search.GlobalSearchScope$FileTypeRestrictionScope.contains(GlobalSearchScope.java:713)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:178)
	at java.base/java.util.Spliterators$IteratorSpliterator.tryAdvance(Spliterators.java:1856)
	at java.base/java.util.stream.StreamSpliterators$WrappingSpliterator.lambda$initPartialTraversalState$0(StreamSpliterators.java:292)
	at java.base/java.util.stream.StreamSpliterators$AbstractWrappingSpliterator.fillBuffer(StreamSpliterators.java:206)
	at java.base/java.util.stream.StreamSpliterators$AbstractWrappingSpliterator.doAdvance(StreamSpliterators.java:161)
	at java.base/java.util.stream.StreamSpliterators$WrappingSpliterator.tryAdvance(StreamSpliterators.java:298)
	at java.base/java.util.Spliterators$1Adapter.hasNext(Spliterators.java:681)
	at com.intellij.util.containers.ContainerUtil.newHashSet(ContainerUtil.java:291)
	at com.intellij.util.indexing.FileBasedIndexEx.getContainingFiles(FileBasedIndexEx.java:241)
	at com.intellij.util.indexing.FileBasedIndexImpl.getContaining
```

**To Reproduce** (*)

**Expected behavior** (*)

**Screenshots**

**Please complete the following information:** (*)

 - OS: Mac OS X 13.5.2
 - PhpStorm/Intellij version: 2023.2.4
 - Plugin Version: 5.1.1

**Additional context**

**Comment by VitaliyBoyko** [comment]
Looks like this one is not related to the plugin but rather:
Abrupt Shutdowns: If the IDE or your system shuts down unexpectedly, cache or index files can become corrupted.
Disk Errors: Issues with your storage device may corrupt files.
