### ISSUE TITLE
Bug Report 2024/01/20

### ISSUE THREAD

**Issue by hungphamlk** [magento/magento2-phpstorm-plugin#1883]
**Describe the bug** (*)

```
com.intellij.util.io.CorruptedException: Storage corrupted /Users/henryp./Library/Caches/JetBrains/PhpStorm2023.3/index/shared_indexes/sih.php.class.alias.name/sih.php.class.alias.name_storage.storage_i
	at com.intellij.util.io.IntToIntBtree$BtreeIndexNodeView.locate(IntToIntBtree.java:911)
	at com.intellij.util.io.IntToIntBtree$BtreeIndexNodeView.access$100(IntToIntBtree.java:308)
	at com.intellij.util.io.IntToIntBtree.get(IntToIntBtree.java:177)
	at com.intellij.util.io.PersistentBTreeEnumerator.enumerateImpl(PersistentBTreeEnumerator.java:584)
	at com.intellij.util.io.PersistentEnumeratorBase.lambda$doEnumerate$0(PersistentEnumeratorBase.java:266)
	at com.intellij.util.io.PersistentEnumeratorBase.catchCorruption(PersistentEnumeratorBase.java:654)
	at com.intellij.util.io.PersistentEnumeratorBase.doEnumerate(PersistentEnumeratorBase.java:265)
	at com.intellij.util.io.PersistentEnumeratorBase.tryEnumerate(PersistentEnumeratorBase.java:256)
	at com.intellij.util.io.PersistentMapImpl.doGet(PersistentMapImpl.java:655)
	at com.intellij.util.io.PersistentMapImpl.get(PersistentMapImpl.java:613)
	at com.intellij.util.indexing.impl.ValueContainerMap.lambda$getModifiableValueContainer$0(ValueContainerMap.java:81)
	at com.intellij.util.indexing.impl.ChangeTrackingValueContainer.getMergedData(ChangeTrackingValueContainer.java:85)
	at com.intellij.util.indexing.impl.ChangeTrackingValueContainer.size(ChangeTrackingValueContainer.java:67)
	at com.intellij.indexing.shared.platform.impl.FileContentHashIndex.lambda$getHashIdToFileIdsFunction$0(FileContentHashIndex.java:76)
	at com.intellij.util.indexing.impl.ValueContainerImpl.readFrom(ValueContainerImpl.java:531)
	at com.intellij.util.indexing.impl.ValueContainerExternalizer.read(ValueContainerExternalizer.java:33)
	at com.intellij.util.indexing.impl.ValueContainerExternalizer.read(ValueContainerExternalizer.java:14)
	at com.intellij.util.io.PersistentMapImpl.doGet(PersistentMapImpl.java:680)
	at com.intellij.util.io.PersistentMapImpl.get(PersistentMapImpl.java:613)
	at com.intellij.util.indexing.impl.ValueContainerMap.lambda$getModifiableValueContainer$0(ValueContainerMap.java:81)
	at com.intellij.util.indexing.impl.ChangeTrackingValueContainer.getMergedData(ChangeTrackingValueContainer.java:85)
	at com.intellij.util.indexing.impl.ChangeTrackingValueContainer.getValueIterator(ChangeTrackingValueContainer.java:72)
	at com.intellij.util.indexing.impl.MergedValueContainer$1.hasNext(MergedValueContainer.java:48)
	at com.intellij.util.indexing.FileBasedIndexEx.lambda$processValuesInScope$8(FileBasedIndexEx.java:358)
	at com.intellij.util.indexing.FileBasedIndexEx.lambda$processValueIterator$9(FileBasedIndexEx.java:389)
	at com.intellij.util.indexing.FileBasedIndexEx.lambda$processExceptions$6(FileBasedIndexEx.java:302)
	at com.intellij.util.ConcurrencyUtil.withLock(ConcurrencyUtil.java:246)
	at com.intellij.util.indexing.FileBasedIndexEx.processExceptions(FileBasedIndexEx.java:302)
	at com.intellij.util.indexing.FileBasedIndexEx.processValueIterator(FileBasedIndexEx.java:391)
	at com.intellij.util.indexing.FileBasedIndexEx.processValuesInScope(FileBasedIndexEx.java:357)
	at com.intellij.util.indexing.FileBasedIndexImpl.processValuesInScope(FileBasedIndexImpl.java:1098)
	at com.intellij.util.indexing.FileBasedIndexEx.getValues(FileBasedIndexEx.java:121)
	at com.jetbrains.php.lang.classAlias.PhpClassAliasIndexImpl.getAliasesByName(PhpClassAliasIndexImpl.java:113)
	at com.jetbrains.php.lang.classAlias.PhpClassAliasIndexImpl.getAliasesByName(PhpClassAliasIndexImpl.java:103)
	at com.jetbrains.php.lang.classAlias.PhpClassAliasIndexImpl.getAllAliasesByName(PhpClassAliasIndexImpl.java:97)
	at com.jetbrains.php.PhpIndexImpl.getAliasesByName(PhpIndexImpl.java:1201)
	at com.jetbrains.php.PhpIndexImpl.addAliases(PhpIndexImpl.java:1254)
	at com.jetbrains.php.PhpIndexImpl.getAnyByFQN(PhpIndexImpl.java:1282)
	at com.magento.idea.magento2plugin.reference.provider.PhpClassReferenceProvider.getReferencesByElement(PhpClassReferenceProvider.java:80)
	at com.magento.idea.magento2plugin.reference.provider.CompositeReferenceProvider.getReferencesByElement(CompositeReferenceProvider.java:30)
	at com.intellij.psi.impl.source.resolve.reference.ReferenceProvidersRegistryImpl.getReferences(ReferenceProvidersRegistryImpl.java:184)
	at com.intellij.psi.impl.source.resolve.reference.ReferenceProvidersRegistryImpl.mapNotEmptyReferencesFromProviders(ReferenceProvidersRegistryImpl.java:165)
	at com.intellij.psi.impl.source.resolve.reference.ReferenceProvidersRegistryImpl.doGetReferencesFromProviders(ReferenceProvidersRegistryImpl.java:144)
	at com.intellij.psi.impl.source.resolve.reference.ReferenceProvidersRegistry.getReferencesFromProviders(ReferenceProvidersRegistry.java:51)
	at com.intellij.psi.impl.source.xml.XmlTokenImpl.getReferences(XmlTokenImpl.java:62)
	at com.intellij.psi.PsiReferenceServiceImpl.doGetReferences(PsiReferenceServiceImpl.java:35)
	at com.intellij.psi.PsiReferenceServiceImpl.getReferences(PsiReferenceServiceImpl.java:25)
	at com.intellij.codeInsight.highlighting.HyperlinkAnnotator.lambda$getReferences$0(HyperlinkAnnotator.java:75)
	at com.intellij.psi.util.CachedValuesManager$1.compute(CachedValuesManager.java:158)
	at com.intellij.psi.impl.PsiCachedValueImpl.doCompute(PsiCachedValueImpl.java:37)
	at com.intellij.util.CachedValueBase.lambda$getValueWithLock$3(CachedValueBase.java:240)
	at com.intellij.util.CachedValueBase.computeData(CachedValueBase.java:43)
	at com.intellij.util.CachedValueBase.lambda$getValueWithLock$4(CachedValueBase.java:240)
	at com.intellij.openapi.util.RecursionManager$1.computePreventingRecursion(RecursionManager.java:111)
	at com.intellij.openapi.util.RecursionGuard.doPreventingRecursion(RecursionGuard.java:27)
	at com.intellij.openapi.util.RecursionManager.doPreventingRecursion(RecursionManager.java:66)
	at com.intellij.util.CachedValueBase.getValueWithLock(CachedValueBase.java:241)
	at com.intellij.psi.impl.PsiCachedValueImpl.getValue(PsiCachedValueImpl.java:27)
	at com.intellij.util.CachedValuesManagerImpl.getCachedValue(CachedValuesManagerImpl.java:69)
	at com.intellij.psi.util.CachedValuesManager.getCachedValue(CachedValuesManager.java:155)
	at com.intellij.psi.util.CachedValuesManager.getCachedValue(CachedValuesManager.java:121)
	at com.intellij.codeInsight.highlighting.HyperlinkAnnotator.getReferences(HyperlinkAnnotator.java:74)
	at com.intellij.codeInsight.hig
```

**To Reproduce** (*)

**Expected behavior** (*)

**Screenshots**

**Please complete the following information:** (*)

 - OS: Mac OS X 14.2.1
 - PhpStorm/Intellij version: 2023.3.2
 - Plugin Version: 5.1.1

**Additional context**

**Comment by VitaliyBoyko** [comment]
Fixed in https://github.com/magento/magento2-phpstorm-plugin/issues/1698
