### ISSUE TITLE
Bug Report 2024/01/24

### ISSUE THREAD

**Issue by ruslanskynix** [magento/magento2-phpstorm-plugin#1895]
**Describe the bug** (*)

```
com.intellij.util.io.CorruptedException: Storage corrupted /home/ruslan/.cache/JetBrains/PhpStorm2023.3/index/com.magento.idea.magento2plugin.stubs.indexes.plugin_to_type/com.magento.idea.magento2plugin.stubs.indexes.plugin_to_type.storage_i
	at com.intellij.util.io.IntToIntBtree$BtreeIndexNodeView.locate(IntToIntBtree.java:911)
	at com.intellij.util.io.IntToIntBtree$BtreeIndexNodeView.access$100(IntToIntBtree.java:308)
	at com.intellij.util.io.IntToIntBtree.get(IntToIntBtree.java:177)
	at com.intellij.util.io.PersistentBTreeEnumerator.enumerateImpl(PersistentBTreeEnumerator.java:584)
	at com.intellij.util.io.PersistentEnumeratorBase.lambda$doEnumerate$0(PersistentEnumeratorBase.java:266)
	at com.intellij.util.io.PersistentEnumeratorBase.catchCorruption(PersistentEnumeratorBase.java:654)
	at com.intellij.util.io.PersistentEnumeratorBase.doEnumerate(PersistentEnumeratorBase.java:265)
	at com.intellij.util.io.PersistentEnumeratorBase.tryEnumerate(PersistentEnumeratorBase.java:256)
	at com.intellij.util.io.PersistentMapImpl.doGet(PersistentMapImpl.java:655)
	at com.intellij.util.io.PersistentMapImpl.get(PersistentMapImpl.java:613)
	at com.intellij.util.indexing.impl.ValueContainerMap.lambda$getModifiableValueContainer$0(ValueContainerMap.java:81)
	at com.intellij.util.indexing.impl.ChangeTrackingValueContainer.getMergedData(ChangeTrackingValueContainer.java:85)
	at com.intellij.util.indexing.impl.ChangeTrackingValueContainer.getValueIterator(ChangeTrackingValueContainer.java:72)
	at com.intellij.util.indexing.impl.MergedValueContainer$1.<init>(MergedValueContainer.java:26)
	at com.intellij.util.indexing.impl.MergedValueContainer.getValueIterator(MergedValueContainer.java:24)
	at com.intellij.util.indexing.impl.MergedValueContainer.getValueIterator(MergedValueContainer.java:11)
	at com.intellij.util.indexing.FileBasedIndexEx.lambda$processValueIterator$9(FileBasedIndexEx.java:388)
	at com.intellij.util.indexing.FileBasedIndexEx.lambda$processExceptions$6(FileBasedIndexEx.java:302)
	at com.intellij.util.ConcurrencyUtil.withLock(ConcurrencyUtil.java:246)
	at com.intellij.util.indexing.FileBasedIndexEx.processExceptions(FileBasedIndexEx.java:302)
	at com.intellij.util.indexing.FileBasedIndexEx.processValueIterator(FileBasedIndexEx.java:391)
	at com.intellij.util.indexing.FileBasedIndexEx.processValuesInScope(FileBasedIndexEx.java:357)
	at com.intellij.util.indexing.FileBasedIndexImpl.processValuesInScope(FileBasedIndexImpl.java:1098)
	at com.intellij.util.indexing.FileBasedIndexEx.getValues(FileBasedIndexEx.java:121)
	at com.magento.idea.magento2plugin.linemarker.php.PluginLineMarkerProvider$PluginClassCache.getPluginsForClass(PluginLineMarkerProvider.java:128)
	at com.magento.idea.magento2plugin.linemarker.php.PluginLineMarkerProvider$PluginClassCache.getPluginsForClass(PluginLineMarkerProvider.java:104)
	at com.magento.idea.magento2plugin.linemarker.php.PluginLineMarkerProvider$MethodPluginCollector.collect(PluginLineMarkerProvider.java:237)
	at com.magento.idea.magento2plugin.linemarker.php.PluginLineMarkerProvider.collectSlowLineMarkers(PluginLineMarkerProvider.java:73)
	at com.intellij.codeInsight.daemon.impl.LineMarkersPass.queryProviders(LineMarkersPass.java:225)
	at com.intellij.codeInsight.daemon.impl.LineMarkersPass.lambda$doCollectMarkers$2(LineMarkersPass.java:107)
	at com.intellij.codeInsight.daemon.impl.Divider.divideInsideAndOutsideInOneRoot(Divider.java:98)
	at com.intellij.codeInsight.daemon.impl.LineMarkersPass.doCollectMarkers(LineMarkersPass.java:103)
	at com.intellij.codeInsight.daemon.impl.LineMarkersPass.doCollectInformation(LineMarkersPass.java:76)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:55)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$1(PassExecutorService.java:406)
	at com.intellij.platform.diagnostic.telemetry.helpers.TraceKt.runWithSpanIgnoreThrows(trace.kt:76)
	at com.intellij.platform.diagnostic.telemetry.helpers.TraceUtil.runWithSpanThrows(TraceUtil.java:34)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$2(PassExecutorService.java:401)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1075)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$3(PassExecutorService.java:392)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$12(CoreProgressManager.java:610)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:685)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:641)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:609)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:78)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.doRun(PassExecutorService.java:391)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$run$0(PassExecutorService.java:367)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:200)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:184)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:365)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:187)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)


```

**To Reproduce** (*)

**Expected behavior** (*)

**Screenshots**

**Please complete the following information:** (*)

 - OS: Linux 6.5.0-14-generic
 - PhpStorm/Intellij version: 2023.3.2
 - Plugin Version: 5.1.1

**Additional context**

**Comment by VitaliyBoyko** [comment]
Fixed in https://github.com/magento/magento2-phpstorm-plugin/issues/1698
