### ISSUE TITLE
** ms to call on EDT NewAclXmlAction#Update@MainMenu

### ISSUE THREAD

**Issue by enricopaladini** [magento/magento2-phpstorm-plugin#1898]
**Describe the bug** (*)

```
com.intellij.diagnostic.PluginException: 589 ms to call on EDT NewAclXmlAction#Update@MainMenu (com.magento.idea.magento2plugin.actions.context.xml.NewAclXmlAction). Revise AnAction.getActionUpdateThread property [Plugin: com.magento.idea.magento2plugin]
	at com.intellij.diagnostic.PluginProblemReporterImpl.createPluginExceptionByClass(PluginProblemReporterImpl.java:23)
	at com.intellij.diagnostic.PluginException.createByClass(PluginException.java:89)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.computeOnEdt(ActionUpdater.kt:223)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.access$computeOnEdt(ActionUpdater.kt:71)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater$computeOnEdt$1.invokeSuspend(ActionUpdater.kt)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
	at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:115)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:103)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)
	Suppressed: java.lang.Throwable: EDT-trace-at-374-ms (5/5)
		at com.intellij.util.io.PagedFileStorage.doGetBufferWrapper(PagedFileStorage.java:443)
		at com.intellij.util.io.PagedFileStorage.getBufferWrapper(PagedFileStorage.java:430)
		at com.intellij.util.io.PagedFileStorage.getByteBuffer(PagedFileStorage.java:191)
		at com.intellij.util.io.IntToIntBtree$BtreeIndexNodeView.lockBuffer(IntToIntBtree.java:475)
		at com.intellij.util.io.IntToIntBtree$BtreeIndexNodeView.syncWithStore(IntToIntBtree.java:461)
		at com.intellij.util.io.IntToIntBtree$BtreeIndexNodeView.setAddress(IntToIntBtree.java:457)
		at com.intellij.util.io.IntToIntBtree$BtreeIndexNodeView.setAddress(IntToIntBtree.java:444)
		at com.intellij.util.io.IntToIntBtree$BtreeRootNode.syncWithStore(IntToIntBtree.java:126)
		at com.intellij.util.io.IntToIntBtree$BtreeRootNode.getNodeView(IntToIntBtree.java:131)
		at com.intellij.util.io.IntToIntBtree.initAccessNodeView(IntToIntBtree.java:203)
		at com.intellij.util.io.IntToIntBtree.get(IntToIntBtree.java:175)
		at com.intellij.util.io.PersistentBTreeEnumerator.enumerateImpl(PersistentBTreeEnumerator.java:584)
		at com.intellij.util.io.PersistentEnumeratorBase.lambda$doEnumerate$0(PersistentEnumeratorBase.java:266)
		at com.intellij.util.io.PersistentEnumeratorBase$$Lambda$1027/0x0000000100af36a0.compute(Unknown Source)
		at com.intellij.util.io.PersistentEnumeratorBase.catchCorruption(PersistentEnumeratorBase.java:654)
		at com.intellij.util.io.PersistentEnumeratorBase.doEnumerate(PersistentEnumeratorBase.java:265)
		at com.intellij.util.io.PersistentEnumeratorBase.tryEnumerate(PersistentEnumeratorBase.java:256)
		at com.intellij.util.io.PersistentMapImpl.doGet(PersistentMapImpl.java:655)
		at com.intellij.util.io.PersistentMapImpl.get(PersistentMapImpl.java:613)
		at com.intellij.util.indexing.impl.ValueContainerMap.lambda$getModifiableValueContainer$0(ValueContainerMap.java:81)
		at com.intellij.util.indexing.impl.ValueContainerMap$$Lambda$2256/0x00000001014b0220.compute(Unknown Source)
		at com.intellij.util.indexing.impl.ChangeTrackingValueContainer.getMergedData(ChangeTrackingValueContainer.java:85)
		at com.intellij.util.indexing.impl.ChangeTrackingValueContainer.getValueIterator(ChangeTrackingValueContainer.java:72)
		at com.intellij.util.indexing.impl.MergedValueContainer$1.<init>(MergedValueContainer.java:26)
		at com.intellij.util.indexing.impl.MergedValueContainer.getValueIterator(MergedValueContainer.java:24)
		at com.intellij.util.indexing.impl.MergedValueContainer.getValueIterator(MergedValueContainer.java:11)
		at com.intellij.util.indexing.ValueContainer.forEach(ValueContainer.java:52)
		at com.intellij.psi.stubs.StubIndexEx.lambda$getContainingIds$12(StubIndexEx.java:391)
		at com.intellij.psi.stubs.StubIndexEx$$Lambda$4097/0x0000000101d0cc00.compute(Unknown Source)
		at com.intellij.util.indexing.IndexUpToDateCheckIn.disableUpToDateCheckIn(IndexUpToDateCheckIn.kt:15)
		at com.intellij.util.indexing.FileBasedIndexEx.disableUpToDateCheckIn(FileBasedIndexEx.java:728)
		at com.intellij.psi.stubs.StubIndexEx.getContainingIds(StubIndexEx.java:387)
		at com.intellij.psi.stubs.StubIndexEx.processElements(StubIndexEx.java:168)
		at com.intellij.psi.stubs.StubIndex.getElements(StubIndex.java:102)
		at com.intellij.psi.stubs.StubIndex.getElements(StubIndex.java:90)
		at com.jetbrains.php.PhpIndexImpl.getElements(PhpIndexImpl.java:746)
		at com.jetbrains.php.PhpIndexImpl.getByName(PhpIndexImpl.java:1183)
		at com.jetbrains.php.PhpIndexImpl.getByFQN(PhpIndexImpl.java:1160)
		at com.jetbrains.php.PhpIndexImpl.getByFqnCacheAware(PhpIndexImpl.java:1241)
		at com.jetbrains.php.PhpIndexImpl.getClassesByFQNInternal(PhpIndexImpl.java:1236)
		at com.jetbrains.php.PhpIndexImpl.getAnyByFQN(PhpIndexImpl.java:1276)
		at com.jetbrains.php.lang.psi.elements.impl.MemberReferenceImpl.findClasses(MemberReferenceImpl.java:331)
		at com.jetbrains.php.lang.psi.elements.impl.MemberReferenceImpl.resolveInHierarchyInner(MemberReferenceImpl.java:231)
		at com.jetbrains.php.lang.psi.elements.impl.MemberReferenceImpl.resolveInHierarchyInner(MemberReferenceImpl.java:202)
		at com.jetbrains.php.lang.psi.elements.impl.MemberReferenceImpl.lambda$resolveInHierarchy$1(MemberReferenceImpl.java:187)
		at com.jetbrains.php.lang.psi.elements.impl.MemberReferenceImpl$$Lambda$5355/0x00000001021170e0.compute(Unknown Source)
		at com.intellij.psi.util.CachedValuesManager$1.compute(CachedValuesManager.java:158)
		at com.intellij.psi.impl.PsiCachedValueImpl.doCompute(PsiCachedValueImpl.java:37)
		at com.intellij.util.CachedValueBase.lambda$getValueWithLock$3(CachedValueBase.java:240)
		at com.intellij.util.CachedVa
```

**To Reproduce** (*)

1. I don't think there are steps to reproduce the behavior. I opened a new project e I saw the error.

**Expected behavior** (*)

Nothing. There must be no errors

**Please complete the following information:** (*)

 - OS: Windows Server 2022 10.0
 - PhpStorm/Intellij version: 2023.3.2
 - Plugin Version: 5.1.1

**Additional context**

**Comment by VitaliyBoyko** [comment]
Duplicate of https://github.com/magento/magento2-phpstorm-plugin/issues/1238
