### ISSUE TITLE
408 ms to call on EDT ContextActionsGroup#Update@ProjectViewPopup

### ISSUE THREAD

**Issue by desaiuttam** [magento/magento2-phpstorm-plugin#1905]
**Describe the bug** (*)

```
com.intellij.diagnostic.PluginException: 408 ms to call on EDT ContextActionsGroup#Update@ProjectViewPopup (com.magento.idea.magento2plugin.actions.groups.ContextActionsGroup). Revise AnAction.getActionUpdateThread property [Plugin: com.magento.idea.magento2plugin]
	at com.intellij.diagnostic.PluginProblemReporterImpl.createPluginExceptionByClass(PluginProblemReporterImpl.java:23)
	at com.intellij.diagnostic.PluginException.createByClass(PluginException.java:89)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.computeOnEdt(ActionUpdater.kt:223)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.access$computeOnEdt(ActionUpdater.kt:71)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater$computeOnEdt$1.invokeSuspend(ActionUpdater.kt)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
	at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:115)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:103)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)
	Suppressed: java.lang.Throwable: EDT-trace-at-118-ms (1/5)
		at java.base@17.0.9/java.lang.ClassLoader.defineClass2(Native Method)
		at java.base@17.0.9/java.lang.ClassLoader.defineClass(ClassLoader.java:1108)
		at app//com.intellij.util.lang.UrlClassLoader.consumeClassData(UrlClassLoader.java:289)
		at app//com.intellij.util.lang.ZipResourceFile.findClass(ZipResourceFile.java:113)
		at app//com.intellij.util.lang.JarLoader.findClass(JarLoader.java:58)
		at app//com.intellij.util.lang.ClassPath.findClassInLoader(ClassPath.java:240)
		at app//com.intellij.util.lang.ClassPath.findClass(ClassPath.java:190)
		at com.intellij.ide.plugins.cl.PluginClassLoader.loadClassInsideSelf(PluginClassLoader.kt:326)
		at com.intellij.ide.plugins.cl.PluginClassLoader.tryLoadingClass(PluginClassLoader.kt:178)
		at com.intellij.serviceContainer.ComponentManagerImplKt.doLoadClass(ComponentManagerImpl.kt:2255)
		at com.intellij.serviceContainer.ComponentManagerImpl.instantiateClass(ComponentManagerImpl.kt:1426)
		at com.intellij.openapi.actionSystem.impl.ActionManagerImplKt.instantiate(ActionManagerImpl.kt:1400)
		at com.intellij.openapi.actionSystem.impl.ActionManagerImplKt.convertStub(ActionManagerImpl.kt:1733)
		at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.getActionImpl(ActionManagerImpl.kt:323)
		at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.getAction(ActionManagerImpl.kt:314)
		at com.intellij.openapi.actionSystem.DefaultActionGroup.getChildren(DefaultActionGroup.java:375)
		at com.intellij.openapi.actionSystem.DefaultActionGroup.getChildren(DefaultActionGroup.java:352)
		at com.magento.idea.magento2plugin.actions.groups.ContextActionsGroup.update(ContextActionsGroup.java:22)
		at com.intellij.openapi.actionSystem.ex.ActionUtil.lambda$performDumbAwareUpdate$0(ActionUtil.java:164)
		at com.intellij.openapi.actionSystem.ex.ActionUtil$$Lambda$1115/0x0000000100bafd28.run(Unknown Source)
		at com.intellij.openapi.actionSystem.ex.ActionUtil.performDumbAwareUpdate(ActionUtil.java:187)
		at com.intellij.openapi.actionSystem.impl.ActionUpdaterKt.doUpdate(ActionUpdater.kt:696)
		at com.intellij.openapi.actionSystem.impl.ActionUpdaterKt.access$doUpdate(ActionUpdater.kt:1)
		at com.intellij.openapi.actionSystem.impl.ActionUpdater$updateActionReal$success$1.invoke(ActionUpdater.kt:110)
		at com.intellij.openapi.actionSystem.impl.ActionUpdater$updateActionReal$success$1.invoke(ActionUpdater.kt:109)
		at com.intellij.openapi.actionSystem.impl.ActionUpdater$callAction$4.invoke(ActionUpdater.kt:178)
		at com.intellij.openapi.actionSystem.impl.ActionUpdater$computeOnEdt$2.invoke(ActionUpdater.kt:204)
		at com.intellij.openapi.actionSystem.impl.ActionUpdater$computeOnEdt$deferred$1$1.invoke(ActionUpdater.kt:468)
		at com.intellij.openapi.progress.CoroutinesKt.blockingContextInner(coroutines.kt:321)
		at com.intellij.openapi.progress.CoroutinesKt.access$blockingContextInner(coroutines.kt:1)
		at com.intellij.openapi.progress.CoroutinesKt$blockingContext$2.invokeSuspend(coroutines.kt:198)
		at com.intellij.openapi.progress.CoroutinesKt$blockingContext$2.invoke(coroutines.kt)
		at com.intellij.openapi.progress.CoroutinesKt$blockingContext$2.invoke(coroutines.kt)
		at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:78)
		at kotlinx.coroutines.CoroutineScopeKt.coroutineScope(CoroutineScope.kt:264)
		at com.intellij.openapi.progress.CoroutinesKt.blockingContext(coroutines.kt:197)
		at com.intellij.openapi.actionSystem.impl.ActionUpdater$computeOnEdt$deferred$1.invokeSuspend(ActionUpdater.kt:467)
		at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
		at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
		at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:280)
		at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:85)
		at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
		at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
		at com.intellij.openapi.actionSystem.impl.UtilsKt$runBlockingForActionExpand$1.invoke(Utils.kt:1108)
		at com.intellij.openapi.actionSystem.impl.UtilsKt$runBlockingForActionExpand$1.invoke(Utils.kt:1105)
		at com.intellij.openapi.progress.ContextKt.prepareThreadContext(context.kt:86)
		at com.intellij.openapi.actionSystem.impl.Utils.expandActionGroupImpl(Utils.kt:1130)
		at com.intellij.openapi.actionSystem.impl.Utils.fillMenu$intellij_platform_ide_impl(Utils.kt:394)
		at com.intellij.openapi.actionSystem.impl.ActionMenu.fillMenu(ActionMenu.kt:405)
		at com.intellij.openapi.actionSystem.impl.ActionMenu.setPopupMenuVisible(ActionMenu.kt:354)
		at java.desktop/javax.swing.JPopupMenu.menuSelectionChanged(JPopupMenu.java:1506)
		at java.desktop/javax.sw
```

**To Reproduce** (*)

**Expected behavior** (*)

**Screenshots**

**Please complete the following information:** (*)

 - OS: Linux 5.8.0-33-generic
 - PhpStorm/Intellij version: 2023.3
 - Plugin Version: 5.1.1

**Additional context**

**Comment by VitaliyBoyko** [comment]
Duplicate of https://github.com/magento/magento2-phpstorm-plugin/issues/1238
