### ISSUE TITLE
Bug Report 2024/04/14

### ISSUE THREAD

**Issue by rhoyle** [magento/magento2-phpstorm-plugin#2021]
**Describe the bug** (*)

```
com.intellij.diagnostic.PluginException: `ActionUpdateThread.OLD_EDT` is deprecated and going to be removed soon. 'com.magento.idea.magento2plugin.actions.context.xml.NewSystemXmlAction' must override `getActionUpdateThread` and chose EDT or BGT. See ActionUpdateThread javadoc. [Plugin: com.magento.idea.magento2plugin]
	at com.intellij.diagnostic.PluginProblemReporterImpl.createPluginExceptionByClass(PluginProblemReporterImpl.java:23)
	at com.intellij.diagnostic.PluginException.createByClass(PluginException.java:90)
	at com.intellij.diagnostic.PluginException.reportDeprecatedUsage(PluginException.java:125)
	at com.intellij.openapi.actionSystem.ActionUpdateThreadAware.getActionUpdateThread(ActionUpdateThreadAware.java:21)
	at com.intellij.openapi.actionSystem.AnAction.getActionUpdateThread(AnAction.java:199)


```

**To Reproduce** (*)

**Expected behavior** (*)

**Screenshots**

**Please complete the following information:** (*)

 - OS: Windows 11.0
 - PhpStorm/Intellij version: 2024.1
 - Plugin Version: 5.1.1

**Additional context**

**Comment by rhoyle** [comment]
my original computer stopped working; so, I had to build a new one.  I was able to use some of the parts from the old one. One of which was the M2 SSD card I also installed a new SSD 1T in the system and set it up as the primary and the old SSD 1t as secondary using the motherboard to switch between the two. Both of them are coming up but the old SSD wants me to setup a new pin however outside of the new SSD I am not able to get the email from my Comcast account. my google account has my old phone number and so I can't use it or change the phone number for it.  Once I click on the Set up my Pin the screen that comes up wants a password How ever I can't tell which Password it is asking for my Microsoft account the Email account that comes up on the screen of what?  The next screen that comes up wants to verify my identity however since I do not have any way to get the code generated by the authenticator app that is imposable, so I clicked on the use a different verification option and that brought up another screen It has; use an authenticator app or Email me at my comcast email then it souse more verification methods which adds a text to a old phone number one of which I changed on my Microsoft account but it is still showing the old one. the next problem is I am routed to a page that tells me to go to https://account.live.com/acsr however what good is that I can't get there from this SSD and when I tried to do it from my phone that did not work either.

This is the problem in a nutshell; I need files that are on the old SSD cark "the old windows 11 system" since it looks like all of the reset of the id verification methides are not working How can I get into my files that are on the old SSD card? " **If the new phone number was coming up as a viable choice, I could do that, but it is not**".

**Comment by VitaliyBoyko** [comment]
Fixed in 5.3.*
