### ISSUE TITLE
java.lang.NullPointerException

### ISSUE THREAD

**Issue by ozkanozgur** [magento/magento2-phpstorm-plugin#2397]
**Describe the bug** (*)

```
java.lang.NullPointerException
	at java.base/java.util.concurrent.ConcurrentHashMap.putVal(ConcurrentHashMap.java:1011)
	at java.base/java.util.concurrent.ConcurrentHashMap.put(ConcurrentHashMap.java:1006)
	at com.intellij.lang.javascript.index.gist.StubValueMap.get(StubValueMap.java:50)
	at com.intellij.lang.javascript.index.gist.JSStubElementGist.getUpToDateOrNullFromGist(JSStubElementGist.java:210)
	at com.intellij.lang.javascript.index.gist.JSStubElementGist.getData(JSStubElementGist.java:142)
	at com.intellij.lang.javascript.index.gist.JSStubElementGist.getData(JSStubElementGist.java:127)
	at com.intellij.lang.javascript.psi.impl.JSCachingTypeOwner.lambda$static$0(JSCachingTypeOwner.java:34)
	at com.intellij.psi.impl.PsiParameterizedCachedValue.doCompute(PsiParameterizedCachedValue.kt:23)
	at com.intellij.util.CachedValueBase.lambda$getValueWithLock$3(CachedValueBase.java:236)
	at com.intellij.util.CachedValueBase.computeData(CachedValueBase.java:43)
	at com.intellij.util.CachedValueBase.lambda$getValueWithLock$4(CachedValueBase.java:236)
	at com.intellij.openapi.util.RecursionManager$1.computePreventingRecursion(RecursionManager.java:111)
	at com.intellij.openapi.util.RecursionGuard.doPreventingRecursion(RecursionGuard.java:27)
	at com.intellij.openapi.util.RecursionManager.doPreventingRecursion(RecursionManager.java:66)
	at com.intellij.util.CachedValueBase.getValueWithLock(CachedValueBase.java:237)
	at com.intellij.psi.impl.PsiParameterizedCachedValue.getValue(PsiParameterizedCachedValue.kt:17)
	at com.intellij.psi.util.CachedValuesManager.getParameterizedCachedValue(CachedValuesManager.java:97)
	at com.intellij.lang.javascript.psi.impl.JSStubElementImpl.getCachedValueStubBuildOptimized(JSStubElementImpl.java:364)
	at com.intellij.lang.javascript.psi.impl.JSCachingTypeOwner.getJSType(JSCachingTypeOwner.java:90)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:575)
	at java.base/java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:260)
	at java.base/java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:616)
	at one.util.streamex.AbstractStreamEx.toArray(AbstractStreamEx.java:390)
	at one.util.streamex.AbstractStreamEx.toMutableList(AbstractStreamEx.java:1345)
	at one.util.streamex.AbstractStreamEx.toList(AbstractStreamEx.java:1326)
	at com.intellij.lang.javascript.psi.types.evaluable.JSQualifiedReferenceType$JSQualifierEvaluator.applyToType(JSQualifiedReferenceType.java:271)
	at com.intellij.lang.javascript.psi.types.evaluable.JSTypeStructuralPartEvaluator.lambda$applyToBaseType$4(JSTypeStructuralPartEvaluator.java:60)
	at com.intellij.lang.javascript.psi.resolve.complexity.JSEvaluationResultElement.transform(JSEvaluationResultElement.java:80)
	at com.intellij.lang.javascript.psi.types.evaluable.JSTypeStructuralPartEvaluator.applyToBaseType(JSTypeStructuralPartEvaluator.java:54)
	at com.intellij.lang.javascript.psi.types.evaluable.JSTypeStructuralPartEvaluator.evaluate(JSTypeStructuralPartEvaluator.java:33)
	at com.intellij.lang.javascript.psi.types.evaluable.JSTypeStructuralPartEvaluator.lambda$applyToBaseType$3(JSTypeStructuralPartEvaluator.java:65)
	at com.intellij.openapi.util.RecursionManager$1.computePreventingRecursion(RecursionManager.java:111)
	at com.intellij.openapi.util.RecursionGuard.doPreventingRecursion(RecursionGuard.java:27)
	at com.intellij.lang.javascript.psi.resolve.JSComplexityAwareRecursionGuard.doPreventingRecursion(JSComplexityAwareRecursionGuard.java:90)
	at com.intellij.lang.javascript.psi.resolve.JSEvaluationRecursionGuard.compute(JSEvaluationRecursionGuard.java:36)
	at com.intellij.lang.javascript.psi.types.evaluable.JSTypeStructuralPartEvaluator.lambda$applyToBaseType$4(JSTypeStructuralPartEvaluator.java:65)
	at com.intellij.lang.javascript.psi.resolve.complexity.JSEvaluationResultElement.transform(JSEvaluationResultElement.java:80)
	at com.intellij.lang.javascript.psi.resolve.complexity.JSEvaluationTaskList.lambda$transform$0(JSEvaluationTaskList.java:36)
	at com.intellij.util.containers.ContainerUtil.map(ContainerUtil.java:1995)
	at com.intellij.lang.javascript.psi.resolve.complexity.JSEvaluationTaskList.transform(JSEvaluationTaskList.java:36)
	at com.intellij.lang.javascript.psi.resolve.complexity.JSEvaluationTaskSet$2.lambda$get$0(JSEvaluationTaskSet.java:53)
	at com.intellij.util.containers.ContainerUtil.map(ContainerUtil.java:1995)
	at com.intellij.lang.javascript.psi.resolve.complexity.JSEvaluationTaskSet$2.get(JSEvaluationTaskSet.java:53)
	at com.intellij.lang.javascript.psi.resolve.complexity.JSEvaluationTaskSet$2.get(JSEvaluationTaskSet.java:50)
	at com.intellij.lang.javascript.psi.resolve.JSEvaluatorComplexityTracker.runTask(JSEvaluatorComplexityTracker.java:67)
	at com.intellij.lang.javascript.psi.resolve.complexity.JSEvaluationTaskSet.transform(JSEvaluationTaskSet.java:50)
	at com.intellij.lang.javascript.psi.types.evaluable.JSTypeStructuralPartEvaluator.applyToBaseType(JSTypeStructuralPartEvaluator.java:54)
	at com.intellij.lang.javascript.psi.types.evaluable.JSTypeStructuralPartEvaluator.evaluate(JSTypeStructuralPartEvaluator.java:33)
	at com.intellij.lang.javascript.psi.types.evaluable.JSQualifiedReferenceType.evaluate(JSQualifiedReferenceType.java:206)
	at com.intellij.lang.javascript.psi.types.evaluable.JSTypeStructuralPartEvaluator.evaluate(JSTypeStructuralPartEvaluator.java:32)
	at com.intellij.lang.javascript.psi.types.evaluable.JSQualifiedReferenceType.evaluate(JSQualifiedReferenceType.java:206)
	at com.intellij.lang.javascript.psi.resolve.JSEvaluableTypeResolver.lambda$doUnwrapRecursivelyInternal$3(JSEvaluableTypeResolver.java:113)
	at com.intellij.openapi.util.RecursionManager$1.computePreventingRecursion(RecursionManager.java:111)
	at com.intellij.openapi.util.RecursionGuard.doPreventingRecursion(RecursionGuard.java:27)
	at com.intellij.lang.javascript.psi.resolve.JSComplexityAwareRecursionGuard.doPreventingRecursion(JSComplexityAwareRecursionGuard.java:90)
	at com.in
```

**To Reproduce** (*)

**Expected behavior** (*)

**Screenshots**

**Please complete the following information:** (*)

 - OS: Mac OS X 14.4
 - PhpStorm/Intellij version: 2024.1.6
 - Plugin Version: 5.3.0

**Additional context**

**Comment by SilinMykola** [comment]
Hello @ozkanozgur! Thank you for your report. Could you please provide more information about how do you get this bug? It will help us to fix it.
Thank you!

**Comment by VitaliyBoyko** [comment]
Looks like not related to the plugin.,
