### ISSUE TITLE
File Templates not listed in 'new file' menu

### ISSUE THREAD

**Issue by riconeitzel** [magento/magento2-phpstorm-plugin#312]
File Templates are shown in the preference pane, but are not listed in 'new file' submenu.

```
Can't find template Magento CLI Command

com.intellij.diagnostic.PluginException: Template not found: Magento CLI Command [Plugin: com.magento.idea.magento2plugin]
	at com.intellij.ide.fileTemplates.impl.FileTemplateManagerImpl.getInternalTemplates(FileTemplateManagerImpl.java:222)
	at com.intellij.ide.fileTemplates.impl.AllFileTemplatesConfigurable.<init>(AllFileTemplatesConfigurable.java:98)
	at com.intellij.ide.fileTemplates.impl.AllFileTemplatesConfigurable$Provider.createConfigurable(AllFileTemplatesConfigurable.java:64)
	at com.intellij.openapi.options.ConfigurableEP$ProviderProducer.createElement(ConfigurableEP.java:399)
	at com.intellij.openapi.options.ConfigurableEP.createConfigurable(ConfigurableEP.java:329)
	at com.intellij.openapi.options.ex.ConfigurableWrapper.createConfigurable(ConfigurableWrapper.java:45)
	at com.intellij.openapi.options.ex.ConfigurableWrapper.getConfigurable(ConfigurableWrapper.java:119)
	at com.intellij.openapi.options.ex.ConfigurableWrapper.cast(ConfigurableWrapper.java:94)
	at com.intellij.openapi.options.ex.ConfigurableCardPanel.prepare(ConfigurableCardPanel.java:44)
	at com.intellij.openapi.options.ex.ConfigurableCardPanel.prepare(ConfigurableCardPanel.java:35)
	at com.intellij.ui.CardLayoutPanel.lambda$selectLater$1(CardLayoutPanel.java:122)
	at com.intellij.util.RunnableCallable.call(RunnableCallable.java:20)
	at com.intellij.util.RunnableCallable.call(RunnableCallable.java:11)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.call(ApplicationImpl.java:268)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.IllegalStateException: Template not found: Magento CLI Command
	at com.intellij.ide.fileTemplates.impl.FileTemplateManagerImpl.getTemplateFromManager(FileTemplateManagerImpl.java:285)
	at com.intellij.ide.fileTemplates.impl.FileTemplateManagerImpl.getJ2eeTemplate(FileTemplateManagerImpl.java:271)
	at com.intellij.ide.fileTemplates.impl.FileTemplateManagerImpl.getInternalTemplate(FileTemplateManagerImpl.java:234)
	at com.intellij.ide.fileTemplates.impl.FileTemplateManagerImpl.getInternalTemplates(FileTemplateManagerImpl.java:219)
	... 21 more
```

PlugIn 

```
Version 1.0.1
```

PHPStorm

```
PhpStorm 2020.2.2
Build #PS-202.7319.77, built on September 23, 2020
Subscription is active until November 20, 2020
Runtime version: 11.0.8+10-b944.31 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 10.15.7
GC: ParNew, ConcurrentMarkSweep
Memory: 1979M
Cores: 16
Registry: run.processes.with.pty=TRUE, debugger.watches.in.variables=false, ide.tooltip.initialDelay=505, ide.balloon.shadow.size=0, nodejs.console.use.terminal=true
Non-Bundled Plugins: String Manipulation, com.chrisrm.idea.MaterialThemeUI, com.github.gitduckhq.intellij-plugin, com.intellij.ideolog, de.netnexus.camelcaseplugin, net.seesharpsoft.intellij.plugins.csv, com.jetbrains.codeWithMe, com.magento.idea.magento2plugin, Magicento, com.kalessil.phpStorm.phpInspectionsUltimate, com.magicento2.magicento2, de.espend.idea.php.annotation, fr.adrienbrault.idea.symfony2plugin
```

OS

```
macOS Version 10.15.7
```

**Comment by VitaliyBoyko** [comment]
Thank you. Already fixed in 2.0.0-develop. To be released soon.
