### ISSUE TITLE
Can't find template Magento Module Ui Grid Collection Data Provider Php

### ISSUE THREAD

**Issue by liemlylac** [magento/magento2-phpstorm-plugin#375]
**Describe the bug** (*) 

Can't find template Magento Module Ui Grid Collection Data Provider Php

com.intellij.diagnostic.PluginException: Template not found: Magento Module Ui Grid Collection Data Provider Php [Plugin: com.magento.idea.magento2plugin]
	at com.intellij.ide.fileTemplates.impl.FileTemplateManagerImpl.getInternalTemplates(FileTemplateManagerImpl.java:222)
	at com.intellij.ide.fileTemplates.impl.AllFileTemplatesConfigurable.<init>(AllFileTemplatesConfigurable.java:98)
	at com.intellij.ide.fileTemplates.impl.AllFileTemplatesConfigurable$Provider.createConfigurable(AllFileTemplatesConfigurable.java:64)
	at com.intellij.openapi.options.ConfigurableEP$ProviderProducer.createElement(ConfigurableEP.java:399)
	at com.intellij.openapi.options.ConfigurableEP.createConfigurable(ConfigurableEP.java:329)
	at com.intellij.openapi.options.ex.ConfigurableWrapper.createConfigurable(ConfigurableWrapper.java:45)
	at com.intellij.openapi.options.ex.ConfigurableWrapper.getConfigurable(ConfigurableWrapper.java:119)
	at com.intellij.openapi.options.ex.ConfigurableWrapper.cast(ConfigurableWrapper.java:94)
	at com.intellij.openapi.options.ex.ConfigurableCardPanel.prepare(ConfigurableCardPanel.java:44)
	at com.intellij.openapi.options.ex.ConfigurableCardPanel.prepare(ConfigurableCardPanel.java:35)
	at com.intellij.ui.CardLayoutPanel.lambda$selectLater$1(CardLayoutPanel.java:122)
	at com.intellij.util.RunnableCallable.call(RunnableCallable.java:20)
	at com.intellij.util.RunnableCallable.call(RunnableCallable.java:11)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.call(ApplicationImpl.java:268)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.IllegalStateException: Template not found: Magento Module Ui Grid Collection Data Provider Php
	at com.intellij.ide.fileTemplates.impl.FileTemplateManagerImpl.getTemplateFromManager(FileTemplateManagerImpl.java:285)
	at com.intellij.ide.fileTemplates.impl.FileTemplateManagerImpl.getJ2eeTemplate(FileTemplateManagerImpl.java:271)
	at com.intellij.ide.fileTemplates.impl.FileTemplateManagerImpl.getInternalTemplate(FileTemplateManagerImpl.java:234)
	at com.intellij.ide.fileTemplates.impl.FileTemplateManagerImpl.getInternalTemplates(FileTemplateManagerImpl.java:219)
	... 21 more

**To Reproduce** (*) 

1. Install Magento2 Plugin.
2. Reopen IDE

**Please complete the following information:** (*) 

 - OS: Windows 10 v2004
 - IntelliJ version: 2020.2.3
 - Plugin Version: 2.0.1

**Comment by drpayyne** [comment]
@magento I am working on this
