### ISSUE TITLE
MapInputException on indexing of require-config.js file from Transsmart module

### ISSUE THREAD

**Issue by boldhedgehog** [magento/magento2-phpstorm-plugin#434]
**Describe the bug** (*) 

PHPStorm reports `MapInputException` exception error while indexing `require-config.js` file from Transsmart module.

**To Reproduce** (*) 

1. Install Transsmart module
2. Open Magento 2 project
3. Wait for PHPStorm to reindex the files
4. Indexing error is reported

```
com.intellij.util.indexing.impl.MapReduceIndex$MapInputException: Failed to map data for input 732689 for index com.magento.idea.magento2plugin.stubs.indexes.require_js
	at com.intellij.util.indexing.impl.MapReduceIndex.mapInputAndPrepareUpdate(MapReduceIndex.java:232)
	at com.intellij.indexing.shared.platform.impl.MergedInvertedIndex.updateBaseIndex(MergedInvertedIndex.java:324)
	at com.intellij.indexing.shared.platform.impl.MergedInvertedIndex.mapInputAndPrepareUpdate(MergedInvertedIndex.java:112)
	at com.intellij.indexing.shared.platform.impl.MergedInvertedIndex.mapInputAndPrepareUpdate(MergedInvertedIndex.java:38)
	at com.intellij.util.indexing.FileBasedIndexImpl.updateSingleIndex(FileBasedIndexImpl.java:1474)
	at com.intellij.util.indexing.FileBasedIndexImpl.lambda$doIndexFileContent$23(FileBasedIndexImpl.java:1356)
	at com.intellij.openapi.fileTypes.impl.FileTypeManagerImpl.freezeFileTypeTemporarilyIn(FileTypeManagerImpl.java:555)
	at com.intellij.util.indexing.FileBasedIndexImpl.doIndexFileContent(FileBasedIndexImpl.java:1326)
	at com.intellij.util.indexing.FileBasedIndexImpl.indexFileContent(FileBasedIndexImpl.java:1253)
	at com.intellij.util.indexing.FileBasedIndexImpl.processRefreshedFile(FileBasedIndexImpl.java:1212)
	at com.intellij.util.indexing.FileBasedIndexImpl$VirtualFileUpdateTask.doProcess(FileBasedIndexImpl.java:1544)
	at com.intellij.util.indexing.FileBasedIndexImpl$VirtualFileUpdateTask.doProcess(FileBasedIndexImpl.java:1541)
	at com.intellij.util.indexing.UpdateTask.process(UpdateTask.java:64)
	at com.intellij.util.indexing.UpdateTask.processAll(UpdateTask.java:33)
	at com.intellij.util.indexing.FileBasedIndexImpl.forceUpdate(FileBasedIndexImpl.java:1563)
	at com.intellij.util.indexing.FileBasedIndexImpl.ensureUpToDate(FileBasedIndexImpl.java:723)
	at com.intellij.psi.stubs.StubIndexImpl.processAllKeys(StubIndexImpl.java:421)
	at com.intellij.psi.stubs.StubIndex.processAllKeys(StubIndex.java:66)
	at com.intellij.psi.stubs.StubIndexImpl.getAllKeys(StubIndexImpl.java:409)
	at com.intellij.lang.javascript.psi.stubs.JSLazyIndexedPackagesIndex.getPackagesToIndex(JSLazyIndexedPackagesIndex.java:73)
	at com.intellij.javascript.nodejs.library.NodeModulesIndexingRulesProvider$updateRequest$1$1.call(NodeModulesIndexingRulesProvider.kt:68)
	at com.intellij.javascript.nodejs.library.NodeModulesIndexingRulesProvider$updateRequest$1$1.call(NodeModulesIndexingRulesProvider.kt:20)
	at com.intellij.openapi.application.impl.NonBlockingReadActionImpl$Submission.insideReadAction(NonBlockingReadActionImpl.java:521)
	at com.intellij.openapi.application.impl.NonBlockingReadActionImpl$Submission.lambda$attemptComputation$3(NonBlockingReadActionImpl.java:468)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1137)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.lambda$runInReadActionWithWriteActionPriority$0(ProgressIndicatorUtils.java:76)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runActionAndCancelBeforeWrite(ProgressIndicatorUtils.java:152)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.lambda$runWithWriteActionPriority$1(ProgressIndicatorUtils.java:113)
	at com.intellij.openapi.progress.ProgressManager.lambda$runProcess$0(ProgressManager.java:59)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:178)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:658)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:610)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:65)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:165)
	at com.intellij.openapi.progress.ProgressManager.runProcess(ProgressManager.java:59)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runWithWriteActionPriority(ProgressIndicatorUtils.java:110)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runInReadActionWithWriteActionPriority(ProgressIndicatorUtils.java:76)
	at com.intellij.openapi.application.impl.NonBlockingReadActionImpl$Submission.attemptComputation(NonBlockingReadActionImpl.java:486)
	at com.intellij.openapi.application.impl.NonBlockingReadActionImpl$Submission.lambda$transferToBgThread$1(NonBlockingReadActionImpl.java:408)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.NullPointerException
	at com.magento.idea.magento2plugin.stubs.indexes.js.RequireJsIndex.parseConfigMap(RequireJsIndex.java:86)
	at com.magento.idea.magento2plugin.stubs.indexes.js.RequireJsIndex.lambda$getIndexer$0(RequireJsIndex.java:48)
	at com.intellij.util.indexing.impl.MapReduceIndex.mapByIndexer(MapReduceIndex.java:291)
	at com.intellij.util.indexing.impl.MapReduceIndex.mapInput(MapReduceIndex.java:283)
	at com.intellij.util.indexing.impl.storage.VfsAwareMapReduceIndex.mapInput(VfsAwareMapReduceIndex.java:168)
	at com.intellij.util.indexing.impl.storage.VfsAwareMapReduceIndex.mapInput(VfsAwareMapReduceIndex.java:46)
	at com.intellij.util.indexing.impl.MapReduceIndex.mapInputAndPrepareUpdate(MapReduceIndex.java:226)
	... 45 more
```

**Expected behavior** (*) 

Files are indexed without errors.

**Please complete the following information:** (*) 

 - OS: Ubuntu Linux 20.04
 - PhpStorm/Intellij version: 2020.3 #PS-203.5981.175, built on December 2, 2020
 - Plugin Version: 3.0.2

**Additional context**

`require-config.js` file:

```
var config = {
    map: {
        "*": {
            "priceUtils": "Magento_Catalog/js/price-utils"
        },
        "markerIcon": "Transsmart_SmartConnect::images/icon-marker.svg",
        "markerHoverIcon": "Transsmart_SmartConnect::images/icon-marker-hover.svg"
    }
};
```

**Comment by drpayyne** [comment]
Hi @boldhedgehog, this syntax seems off. 🤔 Could you please verify if this syntax is right since I can't find it in the docs anywhere. As far as I know, `map` should have a child element which defines the context of the _mapping_ of two modules. For example, a `*` for the context of everything, or `some/module` for the context of that specific module. In your example, children 2 and 3 don't seem to have contexts. This is the reason the indexer is failing.

docs:
- https://requirejs.org/docs/api.html#config-map
- https://devdocs.magento.com/guides/v2.4/javascript-dev-guide/javascript/requirejs.html#requirejs-config-map

**Comment by VitaliyBoyko** [comment]
closing due to inactivity
