### ISSUE TITLE
Array access exception when using "copy path... " action

### ISSUE THREAD

**Issue by mattwellss** [magento/magento2-phpstorm-plugin#495]
**Describe the bug** (*) 

The "copy path..." dialog does not appear when invoking that action, caused by a bug in the Magento2 PhpStorm plugin.

**To Reproduce** (*) 

* Open a Magento2 project in IntelliJ IDEA
* In the "Project" tool window, open the context menu on a file and click "Copy Path..."
* Note that no dialog appears
* Note that there's a new notification (for me, it appears as a flashing red icon in the lower right corner of the editor window... I can't recall if that position of the icon is default or not)

**Expected behavior** (*) 

**Screenshots**

Expected "copy path" dialog (appears when the plugin is disabled)
<img width="546" alt="image" src="https://user-images.githubusercontent.com/1776257/108381727-15589900-71d6-11eb-944a-2d5fea16dcb2.png">

Fatal error when plugin is enabled:
<img width="1478" alt="image" src="https://user-images.githubusercontent.com/1776257/108381916-48029180-71d6-11eb-96d8-3d9072ecc25d.png">

**Please complete the following information:** (*) 

 - macOS 10.15
 - IntelliJ IDEA 2020.3
 - Magento2 PhpStorm plugin version 3.1.1

**Comment by VitaliyBoyko** [comment]
Hi @mattwellss 

Unfortunately, I cannot reproduce it. Could you please specify the exact file path you are trying to copy?

**Comment by DmitryFurs** [comment]
I also encountered this problem, I don't even get a second menu to select the copy option.

**app/design/frontend/Spectrum/default/Magento_Theme/templates/insta.phtml**

```
java.lang.ArrayIndexOutOfBoundsException: Index 3 out of bounds for length 3
	at com.magento.idea.magento2plugin.actions.CopyMagentoPath.getIndexOf(CopyMagentoPath.java:81)
	at com.magento.idea.magento2plugin.actions.CopyMagentoPath.getIndexOf(CopyMagentoPath.java:81)
	at com.magento.idea.magento2plugin.actions.CopyMagentoPath.getIndexOf(CopyMagentoPath.java:81)
	at com.magento.idea.magento2plugin.actions.CopyMagentoPath.getPathToElement(CopyMagentoPath.java:67)
	at com.intellij.ide.actions.CopyPathProvider.getQualifiedName(CopyPathProvider.kt:73)
	at com.intellij.ide.actions.CopyReferencePopup$1$1.customizeComponent(CopyReferencePopup.java:108)
	at com.intellij.ide.actions.CopyReferencePopup$1$1.customizeComponent(CopyReferencePopup.java:64)
	at com.intellij.ui.popup.list.GroupedItemsListRenderer.getListCellRendererComponent(GroupedItemsListRenderer.java:55)
	at com.intellij.ui.ExpandedItemListCellRendererWrapper.getListCellRendererComponent(ExpandedItemListCellRendererWrapper.java:24)
	at com.intellij.ui.components.WideSelectionListUI.updateLayoutState(WideSelectionListUI.java:192)
	at java.desktop/javax.swing.plaf.basic.BasicListUI.maybeUpdateLayoutState(BasicListUI.java:1389)
	at java.desktop/javax.swing.plaf.basic.BasicListUI.getPreferredSize(BasicListUI.java:648)
	at java.desktop/javax.swing.JComponent.getPreferredSize(JComponent.java:1683)
	at com.intellij.ui.components.JBList.getPreferredSize(JBList.java:182)
	at com.intellij.ui.components.JBViewport.getPreferredSizeWithoutScrollBars(JBViewport.java:533)
	at com.intellij.ui.components.JBViewport.getPreferredScrollableViewportSize(JBViewport.java:552)
	at com.intellij.ui.components.JBViewport.getPreferredScrollableViewportSize(JBViewport.java:525)
	at com.intellij.ui.components.JBViewport$1.preferredLayoutSize(JBViewport.java:70)
	at java.desktop/java.awt.Container.preferredSize(Container.java:1823)
	at java.desktop/java.awt.Container.getPreferredSize(Container.java:1807)
	at java.desktop/javax.swing.JComponent.getPreferredSize(JComponent.java:1685)
	at com.intellij.ui.components.JBScrollPane$Layout.preferredLayoutSize(JBScrollPane.java:826)
	at java.desktop/java.awt.Container.preferredSize(Container.java:1823)
	at java.desktop/java.awt.Container.getPreferredSize(Container.java:1807)
	at java.desktop/javax.swing.JComponent.getPreferredSize(JComponent.java:1685)
	at java.desktop/java.awt.BorderLayout.preferredLayoutSize(BorderLayout.java:724)
	at java.desktop/java.awt.Container.preferredSize(Container.java:1823)
	at java.desktop/java.awt.Container.getPreferredSize(Container.java:1807)
	at java.desktop/javax.swing.JComponent.getPreferredSize(JComponent.java:1685)
	at com.intellij.ui.popup.WizardPopup$MyContainer.getPreferredSize(WizardPopup.java:317)
	at com.intellij.ui.popup.AbstractPopup.getSizeForPositioning(AbstractPopup.java:539)
	at com.intellij.ui.popup.AbstractPopup.relativePointByQuickSearch(AbstractPopup.java:525)
	at com.intellij.ui.popup.AbstractPopup.showInBestPositionFor(AbstractPopup.java:474)
	at com.intellij.ide.actions.CopyReferencePopup.actionPerformed(CopyReferencePopup.java:143)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAware(ActionUtil.java:281)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem$ActionTransmitter.lambda$actionPerformed$0(ActionMenuItem.java:310)
	at com.intellij.openapi.wm.impl.FocusManagerImpl.runOnOwnContext(FocusManagerImpl.java:286)
	at com.intellij.openapi.wm.impl.IdeFocusManagerImpl.runOnOwnContext(IdeFocusManagerImpl.java:77)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem$ActionTransmitter.actionPerformed(ActionMenuItem.java:299)
	at java.desktop/javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1967)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem.lambda$fireActionPerformed$0(ActionMenuItem.java:110)
	at com.intellij.openapi.application.TransactionGuardImpl.performUserActivity(TransactionGuardImpl.java:95)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem.fireActionPerformed(ActionMenuItem.java:110)
	at com.intellij.ui.plaf.beg.BegMenuItemUI.doClick(BegMenuItemUI.java:514)
	at com.intellij.ui.plaf.beg.BegMenuItemUI$MyMouseInputHandler.mouseReleased(BegMenuItemUI.java:544)
	at java.desktop/java.awt.Component.processMouseEvent(Component.java:6652)
	at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3345)
	at java.desktop/java.awt.Component.processEvent(Component.java:6417)
	at java.desktop/java.awt.Container.processEvent(Container.java:2263)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5027)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2321)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4859)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4918)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4547)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4488)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2307)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2780)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4859)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:778)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:751)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:749)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:748)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:976)
	at com.intellij.ide.IdeEventQueue.dispatchMouseEvent(IdeEventQueue.java:911)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:840)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:454)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:773)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$9(IdeEventQueue.java:453)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:822)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:507)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```
