### ISSUE TITLE
Error in the console  (New Module Action)

### ISSUE THREAD

**Issue by VitaliyBoyko** [magento/magento2-phpstorm-plugin#501]
**Describe the bug** (*) 

```
update failed for AnAction(com.magento.idea.magento2plugin.actions.generation.NewModuleAction) with ID=Magento2NewModule

java.lang.ArrayIndexOutOfBoundsException: Index 2 out of bounds for length 2
	at com.magento.idea.magento2plugin.util.magento.GetModuleNameByDirectoryUtil.execute(GetModuleNameByDirectoryUtil.java:40)
	at com.magento.idea.magento2plugin.actions.generation.NewModuleAction.update(NewModuleAction.java:90)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performDumbAwareUpdate(ActionUtil.java:178)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.doUpdate(ActionUpdater.java:465)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.lambda$new$1(ActionUpdater.java:94)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.callAction(ActionUpdater.java:134)
```

**To Reproduce** (*) 

No specific steps

**Screenshots**

**Please complete the following information:** (*) 

 - OS: all
 - PhpStorm/Intellij version: 2020.3.2
 - Plugin Version: 3.1.2

**Comment by tinhnd2** [comment]
I'm working on this.

**Comment by dylanngo95** [comment]
Hi @VitaliyBoyko 
Can you help me review my pull request?
https://github.com/magento/magento2-phpstorm-plugin/pull/519
Thanks.
