### ISSUE TITLE
Reindex critical error during casting to XmlFile

### ISSUE THREAD

**Issue by bohdan-harniuk** [magento/magento2-phpstorm-plugin#608]
**Describe the bug** (*)

An exception during reindex process. It occurs from time to time. I noticed this issue when I was generating before plugin for a class method.

```
java.lang.ClassCastException: class com.jetbrains.php.lang.psi.PhpFileImpl cannot be cast to class com.intellij.psi.xml.XmlFile (com.jetbrains.php.lang.psi.PhpFileImpl is in unnamed module of loader com.intellij.ide.plugins.cl.PluginClassLoader @3ec18d21; com.intellij.psi.xml.XmlFile is in unnamed module of loader com.intellij.util.lang.PathClassLoader @2ef9b8bc)
	at com.magento.idea.magento2plugin.indexes.XmlIndex.getPhpClassDeclarations(XmlIndex.java:50)
	at com.magento.idea.magento2plugin.linemarker.php.ClassConfigurationLineMarkerProvider.collectSlowLineMarkers(ClassConfigurationLineMarkerProvider.java:46)
	at com.intellij.codeInsight.daemon.impl.LineMarkersPass.queryProviders(LineMarkersPass.java:181)
	at com.intellij.codeInsight.daemon.impl.LineMarkersPass.lambda$doCollectInformation$3(LineMarkersPass.java:90)
	at com.intellij.codeInsight.daemon.impl.Divider.divideInsideAndOutsideInOneRoot(Divider.java:81)
	at com.intellij.codeInsight.daemon.impl.LineMarkersPass.doCollectInformation(LineMarkersPass.java:77)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:56)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$1(PassExecutorService.java:400)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1096)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$2(PassExecutorService.java:393)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:688)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:634)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:64)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.doRun(PassExecutorService.java:392)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$run$0(PassExecutorService.java:368)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:167)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:178)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:366)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:188)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)

```

**Expected behavior** (*)

No such critical errors are expected to happen during the reindexing process.

**Please complete the following information:** (*)

 - OS: Mac OS X 10.16
 - PhpStorm/Intellij version: 2021.1
 - Plugin Version: 4.0.0

**Comment by bohdan-harniuk** [comment]
@magento I am working on this
