### ISSUE TITLE
[Bug] ClassCastException: PsiPlainTextFileImpl cannot be cast to class XmlFile in WebApiTypeIndex

### ISSUE THREAD

**Issue by Taral-Patoliya** [magento/magento2-phpstorm-plugin#654]
**Describe the bug** (*)

```
java.lang.ClassCastException: class com.intellij.psi.impl.source.PsiPlainTextFileImpl cannot be cast to class com.intellij.psi.xml.XmlFile (com.intellij.psi.impl.source.PsiPlainTextFileImpl and com.intellij.psi.xml.XmlFile are in unnamed module of loader com.intellij.util.lang.PathClassLoader @5ebec15)
	at com.magento.idea.magento2plugin.stubs.indexes.WebApiTypeIndex.getWebApiRoutes(WebApiTypeIndex.java:131)
	at com.magento.idea.magento2plugin.linemarker.php.WebApiLineMarkerProvider$WebApiRoutesCollector.extractRoutesForMethod(WebApiLineMarkerProvider.java:118)
	at com.magento.idea.magento2plugin.linemarker.php.WebApiLineMarkerProvider$WebApiRoutesCollector.extractRoutesForMethod(WebApiLineMarkerProvider.java:126)
	at com.magento.idea.magento2plugin.linemarker.php.WebApiLineMarkerProvider$WebApiRoutesCollector.getRoutes(WebApiLineMarkerProvider.java:104)
	at com.magento.idea.magento2plugin.linemarker.php.WebApiLineMarkerProvider.collectSlowLineMarkers(WebApiLineMarkerProvider.java:48)
	at com.intellij.codeInsight.daemon.impl.LineMarkersPass.queryProviders(LineMarkersPass.java:185)
	at com.intellij.codeInsight.daemon.impl.LineMarkersPass.lambda$doCollectInformation$3(LineMarkersPass.java:90)
	at com.intellij.codeInsight.daemon.impl.Divider.divideInsideAndOutsideInOneRoot(Divider.java:81)
	at com.intellij.codeInsight.daemon.impl.LineMarkersPass.doCollectInformation(LineMarkersPass.java:77)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:56)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$1(PassExecutorService.java:414)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1078)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$2(PassExecutorService.java:407)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:705)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:647)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:63)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.doRun(PassExecutorService.java:406)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$run$0(PassExecutorService.java:382)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:174)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:183)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:380)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:188)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)

```

**To Reproduce** (*)

**Expected behavior** (*)

**Screenshots**

**Please complete the following information:** (*)

 - OS: Mac OS X 11.5.2
 - PhpStorm/Intellij version: 2021.2.2
 - Plugin Version: 4.1.0

**Additional context**

**Comment by bohdan-harniuk** [comment]
Hello, @Taral-Patoliya!

Thank you for your report!
We'll try to deliver fix in the next bug-fix release!

Thank you!

**Comment by bohdan-harniuk** [comment]
Hello, @Taral-Patoliya!

This issue has been fixed and will be delivered in the upcoming release: 4.2.2.

Thanks, Bohdan
