### ISSUE TITLE
Bug Report 2021/10/29

### ISSUE THREAD

**Issue by magentopits** [magento/magento2-phpstorm-plugin#696]
**Describe the bug** (*)

```
java.lang.StackOverflowError
	at com.intellij.psi.impl.source.PsiFileImpl.getStubTree(PsiFileImpl.java:620)
	at com.intellij.psi.impl.source.PsiFileImpl.getGreenStubTree(PsiFileImpl.java:953)
	at com.intellij.psi.impl.source.SpineRef.getGreenStub(SpineRef.java:39)
	at com.intellij.extapi.psi.StubBasedPsiElementBase.getGreenStub(StubBasedPsiElementBase.java:352)
	at com.jetbrains.php.lang.psi.elements.impl.PhpNamedElementImpl.getName(PhpNamedElementImpl.java:70)
	at com.jetbrains.php.lang.psi.elements.impl.PhpNamedElementImpl.getFQN(PhpNamedElementImpl.java:124)
	at com.intellij.util.containers.ContainerUtil.map2Set(ContainerUtil.java:2701)
	at com.jetbrains.php.lang.psi.elements.impl.ClassReferenceImpl.getLocalFQN(ClassReferenceImpl.java:347)
	at com.jetbrains.php.lang.psi.elements.impl.ClassReferenceImpl.getFQN(ClassReferenceImpl.java:341)
	at com.jetbrains.php.lang.psi.elements.impl.PhpClassImpl.getSuperFQN(PhpClassImpl.java:407)
	at com.jetbrains.php.PhpClassHierarchyUtils.getSuperClasses(PhpClassHierarchyUtils.java:433)
	at com.jetbrains.php.lang.psi.elements.impl.PhpClassImpl.getSuperClasses(PhpClassImpl.java:425)
	at com.jetbrains.php.lang.psi.elements.impl.PhpClassImpl.getSupers(PhpClassImpl.java:724)
	at com.magento.idea.magento2plugin.linemarker.php.PluginLineMarkerProvider$PluginClassCache.getPluginsForClass(PluginLineMarkerProvider.java:98)
	at com.magento.idea.magento2plugin.linemarker.php.PluginLineMarkerProvider$PluginClassCache.getPluginsForClass(PluginLineMarkerProvider.java:99)
	at com.magento.idea.magento2plugin.linemarker.php.PluginLineMarkerProvider$PluginClassCache.getPluginsForClass(PluginLineMarkerProvider.java:99)
	at com.magento.idea.magento2plugin.linemarker.php.PluginLineMarkerProvider$PluginClassCache.getPluginsForClass(PluginLineMarkerProvider.java:99)
	at com.magento.idea.magento2plugin.linemarker.php.PluginLineMarkerProvider$PluginClassCache.getPluginsForClass(PluginLineMarkerProvider.java:99)
	at com.magento.idea.magento2plugin.linemarker.php.PluginLineMarkerProvider$PluginClassCache.getPluginsForClass(PluginLineMarkerProvider.java:99)
	at com.magento.idea.magento2plugin.linemarker.php.PluginLineMarkerProvider$PluginClassCache.getPluginsForClass(PluginLineMarkerProvider.java:99)
	at com.magento.idea.magento2plugin.linemarker.php.PluginLineMarkerProvider$PluginClassCache.getPluginsForClass(PluginLineMarkerProvider.java:99)
	at com.magento.idea.magento2plugin.linemarker.php.PluginLineMarkerProvider$PluginClassCache.getPluginsForClass(PluginLineMarkerProvider.java:99)
	at com.magento.idea.magento2plugin.linemarker.php.PluginLineMarkerProvider$PluginClassCache.getPluginsForClass(PluginLineMarkerProvider.java:99)
	at com.magento.idea.magento2plugin.linemarker.php.PluginLineMarkerProvider$PluginClassCache.getPluginsForClass(PluginLineMarkerProvider.java:99)
	at com.magento.idea.magento2plugin.linemarker.php.PluginLineMarkerProvider$PluginClassCache.getPluginsForClass(PluginLineMarkerProvider.java:99)
	at com.magento.idea.magento2plugin.linemarker.php.PluginLineMarkerProvider$PluginClassCache.getPluginsForClass(PluginLineMarkerProvider.java:99)
	at com.magento.idea.magento2plugin.linemarker.php.PluginLineMarkerProvider$PluginClassCache.getPluginsForClass(PluginLineMarkerProvider.java:99)
	at com.magento.idea.magento2plugin.linemarker.php.PluginLineMarkerProvider$PluginClassCache.getPluginsForClass(PluginLineMarkerProvider.java:99)
	at com.magento.idea.magento2plugin.linemarker.php.PluginLineMarkerProvider$PluginClassCache.getPluginsForClass(PluginLineMarkerProvider.java:99)
	at com.magento.idea.magento2plugin.linemarker.php.PluginLineMarkerProvider$PluginClassCache.getPluginsForClass(PluginLineMarkerProvider.java:99)
	at com.magento.idea.magento2plugin.linemarker.php.PluginLineMarkerProvider$PluginClassCache.getPluginsForClass(PluginLineMarkerProvider.java:99)
	at com.magento.idea.magento2plugin.linemarker.php.PluginLineMarkerProvider$PluginClassCache.getPluginsForClass(PluginLineMarkerProvider.java:99)
	at com.magento.idea.magento2plugin.linemarker.php.PluginLineMarkerProvider$PluginClassCache.getPluginsForClass(PluginLineMarkerProvider.java:99)
	at com.magento.idea.magento2plugin.linemarker.php.PluginLineMarkerProvider$PluginClassCache.getPluginsForClass(PluginLineMarkerProvider.java:99)
	at com.magento.idea.magento2plugin.linemarker.php.PluginLineMarkerProvider$PluginClassCache.getPluginsForClass(PluginLineMarkerProvider.java:99)
	at com.magento.idea.magento2plugin.linemarker.php.PluginLineMarkerProvider$PluginClassCache.getPluginsForClass(PluginLineMarkerProvider.java:99)
	at com.magento.idea.magento2plugin.linemarker.php.PluginLineMarkerProvider$PluginClassCache.getPluginsForClass(PluginLineMarkerProvider.java:99)
	at com.magento.idea.magento2plugin.linemarker.php.PluginLineMarkerProvider$PluginClassCache.getPluginsForClass(PluginLineMarkerProvider.java:99)
	at com.magento.idea.magento2plugin.linemarker.php.PluginLineMarkerProvider$PluginClassCache.getPluginsForClass(PluginLineMarkerProvider.java:99)
	at com.magento.idea.magento2plugin.linemarker.php.PluginLineMarkerProvider$PluginClassCache.getPluginsForClass(PluginLineMarkerProvider.java:99)
	at com.magento.idea.magento2plugin.linemarker.php.PluginLineMarkerProvider$PluginClassCache.getPluginsForClass(PluginLineMarkerProvider.java:99)
	at com.magento.idea.magento2plugin.linemarker.php.PluginLineMarkerProvider$PluginClassCache.getPluginsForClass(PluginLineMarkerProvider.java:99)
	at com.magento.idea.magento2plugin.linemarker.php.PluginLineMarkerProvider$PluginClassCache.getPluginsForClass(PluginLineMarkerProvider.java:99)
	at com.magento.idea.magento2plugin.linemarker.php.PluginLineMarkerProvider$PluginClassCache.getPluginsForClass(PluginLineMarkerProvider.java:99)
	at com.magento.idea.magento2plugin.linemarker.php.PluginLineMarkerProvider$PluginClassCache.getPluginsForClass(PluginLineMarkerProvider.java:99)
	at com.magento.idea.magento2plugin.linemarker.php.PluginLineMarkerProvider$PluginClassCache.getPluginsForClass(PluginLineMarkerProvider.java:99)
	at com.magento.idea.magento2plugin.linemarker.php.PluginLineMarkerProvider$PluginClassCache.getPluginsForClass(PluginLineMarkerProvider.java:99)
	at com.magento.idea.magento2plugin.linemarker.php.PluginLineMarkerProvider$PluginClassCache.getPluginsForClass(PluginLineMarkerProvider.java:99)
	at com.magento.idea.magento2plugin.linemarker.php.PluginLineMarkerProvider$PluginClassCache.ge
```

**To Reproduce** (*)

**Expected behavior** (*)

**Screenshots**

**Please complete the following information:** (*)

 - OS: Windows 10 10.0
 - PhpStorm/Intellij version: 2021.2.2
 - Plugin Version: 4.1.0

**Additional context**

**Comment by bohdan-harniuk** [comment]
Hello, @magentopits!
Thank you for your report!

It will be resolved in the #765.
I am closing this issue as duplicated. 

Thank you!
