### ISSUE TITLE
Bug Report 2021/11/04

### ISSUE THREAD

**Issue by zakharevych** [magento/magento2-phpstorm-plugin#734]
**Describe the bug** (*)

```
java.lang.StackOverflowError
	at java.base/java.lang.ThreadLocal.get(ThreadLocal.java:163)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.isReadLockedByThisThread(ReadMostlyRWLock.java:89)
	at com.intellij.openapi.application.impl.ApplicationImpl.isReadAccessAllowed(ApplicationImpl.java:998)
	at com.intellij.openapi.application.impl.ApplicationImpl.assertReadAccessAllowed(ApplicationImpl.java:968)
	at com.intellij.psi.impl.source.PsiFileImpl.assertReadAccessAllowed(PsiFileImpl.java:181)
	at com.intellij.psi.impl.source.PsiFileImpl.getStubTree(PsiFileImpl.java:618)
	at com.intellij.psi.impl.source.PsiFileImpl.getGreenStubTree(PsiFileImpl.java:953)
	at com.intellij.psi.impl.source.SpineRef.getGreenStub(SpineRef.java:39)
	at com.intellij.extapi.psi.StubBasedPsiElementBase.getGreenStub(StubBasedPsiElementBase.java:352)
	at com.intellij.extapi.psi.StubBasedPsiElementBase.getParent(StubBasedPsiElementBase.java:314)
	at com.intellij.psi.util.PsiTreeUtil.getParentOfType(PsiTreeUtil.java:647)
	at com.intellij.psi.util.PsiTreeUtil.getParentOfType(PsiTreeUtil.java:624)
	at com.intellij.psi.util.PsiTreeUtil.getParentOfType(PsiTreeUtil.java:547)
	at com.jetbrains.php.lang.psi.elements.impl.ClassReferenceImpl.isInForeignFunction(ClassReferenceImpl.java:267)
	at com.jetbrains.php.lang.psi.elements.impl.ClassReferenceImpl.resolveLocal(ClassReferenceImpl.java:232)
	at com.jetbrains.php.lang.psi.elements.impl.ClassReferenceImpl.resolveLocal(ClassReferenceImpl.java:224)
	at com.jetbrains.php.lang.psi.elements.impl.ClassReferenceImpl.getLocalFQN(ClassReferenceImpl.java:346)
	at com.jetbrains.php.lang.psi.elements.impl.ClassReferenceImpl.getFQN(ClassReferenceImpl.java:341)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.base/java.util.AbstractList$RandomAccessSpliterator.forEachRemaining(AbstractList.java:720)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:550)
	at java.base/java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:260)
	at java.base/java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:517)
	at one.util.streamex.StreamEx.toArray(StreamEx.java:840)
	at com.jetbrains.php.lang.psi.elements.impl.PhpClassImpl.getInterfaceNames(PhpClassImpl.java:489)
	at com.jetbrains.php.lang.psi.elements.PhpClass.getDirectImplementedInterfaces(PhpClass.java:84)
	at com.jetbrains.php.lang.psi.elements.impl.PhpClassImpl.getImplementedInterfaces(PhpClassImpl.java:494)
	at com.jetbrains.php.lang.psi.elements.impl.PhpClassImpl.getSupers(PhpClassImpl.java:725)
	at com.magento.idea.magento2plugin.linemarker.php.PluginLineMarkerProvider$PluginClassCache.getPluginsForClass(PluginLineMarkerProvider.java:98)
	at com.magento.idea.magento2plugin.linemarker.php.PluginLineMarkerProvider$PluginClassCache.getPluginsForClass(PluginLineMarkerProvider.java:99)
	at com.magento.idea.magento2plugin.linemarker.php.PluginLineMarkerProvider$PluginClassCache.getPluginsForClass(PluginLineMarkerProvider.java:99)
	at com.magento.idea.magento2plugin.linemarker.php.PluginLineMarkerProvider$PluginClassCache.getPluginsForClass(PluginLineMarkerProvider.java:99)
	at com.magento.idea.magento2plugin.linemarker.php.PluginLineMarkerProvider$PluginClassCache.getPluginsForClass(PluginLineMarkerProvider.java:99)
	at com.magento.idea.magento2plugin.linemarker.php.PluginLineMarkerProvider$PluginClassCache.getPluginsForClass(PluginLineMarkerProvider.java:99)
	at com.magento.idea.magento2plugin.linemarker.php.PluginLineMarkerProvider$PluginClassCache.getPluginsForClass(PluginLineMarkerProvider.java:99)
	at com.magento.idea.magento2plugin.linemarker.php.PluginLineMarkerProvider$PluginClassCache.getPluginsForClass(PluginLineMarkerProvider.java:99)
	at com.magento.idea.magento2plugin.linemarker.php.PluginLineMarkerProvider$PluginClassCache.getPluginsForClass(PluginLineMarkerProvider.java:99)
	at com.magento.idea.magento2plugin.linemarker.php.PluginLineMarkerProvider$PluginClassCache.getPluginsForClass(PluginLineMarkerProvider.java:99)
	at com.magento.idea.magento2plugin.linemarker.php.PluginLineMarkerProvider$PluginClassCache.getPluginsForClass(PluginLineMarkerProvider.java:99)
	at com.magento.idea.magento2plugin.linemarker.php.PluginLineMarkerProvider$PluginClassCache.getPluginsForClass(PluginLineMarkerProvider.java:99)
	at com.magento.idea.magento2plugin.linemarker.php.PluginLineMarkerProvider$PluginClassCache.getPluginsForClass(PluginLineMarkerProvider.java:99)
	at com.magento.idea.magento2plugin.linemarker.php.PluginLineMarkerProvider$PluginClassCache.getPluginsForClass(PluginLineMarkerProvider.java:99)
	at com.magento.idea.magento2plugin.linemarker.php.PluginLineMarkerProvider$PluginClassCache.getPluginsForClass(PluginLineMarkerProvider.java:99)
	at com.magento.idea.magento2plugin.linemarker.php.PluginLineMarkerProvider$PluginClassCache.getPluginsForClass(PluginLineMarkerProvider.java:99)
	at com.magento.idea.magento2plugin.linemarker.php.PluginLineMarkerProvider$PluginClassCache.getPluginsForClass(PluginLineMarkerProvider.java:99)
	at com.magento.idea.magento2plugin.linemarker.php.PluginLineMarkerProvider$PluginClassCache.getPluginsForClass(PluginLineMarkerProvider.java:99)
	at com.magento.idea.magento2plugin.linemarker.php.PluginLineMarkerProvider$PluginClassCache.getPluginsForClass(PluginLineMarkerProvider.java:99)
	at com.magento.idea.magento2plugin.linemarker.php.PluginLineMarkerProvider$PluginClassCache.getPluginsForClass(PluginLineMarkerProvider.java:99)
	at com.magento.idea.magento2plugin.linemarker.php.PluginLineMarkerProvider$PluginClassCache.getPluginsForClass(PluginLineMarkerProvider.java:99)
	at com.magento.idea.magento2plugin.linemarker.php.PluginLineMarkerProvider$PluginClassCache.getPluginsForClass(PluginLineMarkerProvider.java:99)
	at com.magento.idea.magento2plugin.linemarker.php.PluginLineMarkerProvider$PluginClassCache.getPluginsForClass(PluginLineMarkerProvider.java:99)
	at com.magento.idea.magento2plugin.linemarker.php.PluginLineMarkerProvider$PluginClassCache.getPluginsForClass(PluginLineMarkerProvider.java:99)
	at com.magento.idea.magento2plugin.linemarker.php.PluginLineMarkerProvider$PluginClassCache.getPluginsForClass(PluginLineMarkerProvider.java:99)
	at com.magento.idea.magento2plugin.linemarker.php.PluginLineMarkerProvider$PluginClass
```

**To Reproduce** (*)

**Expected behavior** (*)

**Screenshots**

**Please complete the following information:** (*)

 - OS: Mac OS X 11.6
 - PhpStorm/Intellij version: 2021.2.2
 - Plugin Version: 4.1.0

**Additional context**

**Comment by bohdan-harniuk** [comment]
Hello, @zakharevych!
Thank you for your report!

It will be resolved in the #765.
I am closing this issue as duplicated.

Thank you!
