### ISSUE TITLE
[Bug] Empty PSI elements must not be passed to createDescriptor (PluginInspection.java:294)

### ISSUE THREAD

**Issue by AboElnoor** [magento/magento2-phpstorm-plugin#739]
**Describe the bug** (*)

```
java.lang.Throwable: Empty PSI elements must not be passed to createDescriptor. Start: ParameterImpl: %EMPTY%, end: ParameterImpl: %EMPTY%, startContainingFile: PHP file
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:182)
	at com.intellij.codeInspection.ProblemDescriptorBase.<init>(ProblemDescriptorBase.java:64)
	at com.intellij.codeInspection.InspectionManagerBase.createProblemDescriptor(InspectionManagerBase.java:72)
	at com.intellij.codeInspection.InspectionManagerBase.createProblemDescriptor(InspectionManagerBase.java:60)
	at com.intellij.codeInspection.ProblemsHolder.registerProblem(ProblemsHolder.java:52)
	at com.magento.idea.magento2plugin.inspections.php.PluginInspection$1.checkParametersCompatibility(PluginInspection.java:294)
	at com.magento.idea.magento2plugin.inspections.php.PluginInspection$1.visitPhpMethod(PluginInspection.java:107)
	at com.jetbrains.php.lang.psi.elements.impl.MethodImpl.accept(MethodImpl.java:89)
	at com.jetbrains.php.lang.psi.elements.impl.PhpPsiElementImpl.accept(PhpPsiElementImpl.java:73)
	at com.intellij.codeInspection.InspectionEngine.acceptElements(InspectionEngine.java:64)
	at com.intellij.codeInspection.InspectionEngine.createVisitorAndAcceptElements(InspectionEngine.java:55)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.runToolOnElements(LocalInspectionsPass.java:326)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.lambda$visitPriorityElementsAndInit$4(LocalInspectionsPass.java:285)
	at com.intellij.util.AstLoadingFilter.forceAllowTreeLoading(AstLoadingFilter.java:159)
	at com.intellij.util.AstLoadingFilter.forceAllowTreeLoading(AstLoadingFilter.java:151)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.lambda$visitPriorityElementsAndInit$5(LocalInspectionsPass.java:283)
	at com.intellij.util.AstLoadingFilter.disallowTreeLoading(AstLoadingFilter.java:130)
	at com.intellij.util.AstLoadingFilter.disallowTreeLoading(AstLoadingFilter.java:119)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.lambda$visitPriorityElementsAndInit$6(LocalInspectionsPass.java:283)
	at com.intellij.concurrency.ApplierCompleter.execAndForkSubTasks(ApplierCompleter.java:136)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1078)
	at com.intellij.concurrency.ApplierCompleter.lambda$wrapInReadActionAndIndicator$1(ApplierCompleter.java:92)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:705)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:647)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:63)
	at com.intellij.concurrency.ApplierCompleter.wrapInReadActionAndIndicator(ApplierCompleter.java:104)
	at com.intellij.concurrency.ApplierCompleter.lambda$compute$0(ApplierCompleter.java:83)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:174)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:183)
	at com.intellij.concurrency.ApplierCompleter.compute(ApplierCompleter.java:83)
	at java.base/java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:746)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)

```

**To Reproduce** (*)

**Expected behavior** (*)

**Screenshots**

**Please complete the following information:** (*)

 - OS: Linux 5.11.0-38-generic
 - PhpStorm/Intellij version: 2021.2.3
 - Plugin Version: 4.1.0

**Additional context**

**Comment by bohdan-harniuk** [comment]
Hello, @AboElnoor!

Thank you for your report!
We'll try to deliver fix in the next bug-fix release!

Thank you!

**Comment by bohdan-harniuk** [comment]
Hello, @AboElnoor!

This bug is reproduced:

<img width="1448" alt="Screenshot 2021-11-30 at 15 05 36" src="https://user-images.githubusercontent.com/31848341/144061918-988ba5fe-4755-42fe-8480-1b3412976ddc.png">

It will be fixed and delivered with the next bug-fix release (4.2.1).

Thanks, Bohdan

**Comment by bohdan-harniuk** [comment]
This bug is fixed, but also found for the PHP plugin (it is PHPStorm):

<img width="1409" alt="Screenshot 2021-11-30 at 15 32 02" src="https://user-images.githubusercontent.com/31848341/144066468-d72b2195-56eb-42ac-9160-b37b1a1daaff.png">

This inspection can be found here:

<img width="1098" alt="Screenshot 2021-11-30 at 15 31 29" src="https://user-images.githubusercontent.com/31848341/144066414-e1e8c353-6f43-450f-a142-d836135958d4.png">

@AboElnoor, we will deliver fix for this bug in the our plugin in the next release. 
About the same issue for the PHP, you can just ignore it for now. I will open an issue for the PHPStorm.

Thanks, Bohdan

**Comment by bohdan-harniuk** [comment]
I've opened an issue about mentioned bug in the PHPStorm: https://youtrack.jetbrains.com/issue/WI-64186

cc. @AboElnoor
