### ISSUE TITLE
Bug Report 2021/11/10

### ISSUE THREAD

**Issue by mdxacura2011** [magento/magento2-phpstorm-plugin#745]
**Describe the bug** (*)

```
java.lang.StackOverflowError
	at com.intellij.openapi.progress.ProgressManager.checkCanceled(ProgressManager.java:231)
	at com.intellij.openapi.progress.ProgressIndicatorProvider.checkCanceled(ProgressIndicatorProvider.java:23)
	at com.intellij.psi.impl.source.tree.CompositeElement.getPsi(CompositeElement.java:687)
	at com.intellij.psi.impl.source.SourceTreeToPsiMap.treeElementToPsi(SourceTreeToPsiMap.java:16)
	at com.intellij.psi.impl.source.tree.SharedImplUtil.getParent(SharedImplUtil.java:33)
	at com.intellij.extapi.psi.ASTWrapperPsiElement.getParent(ASTWrapperPsiElement.java:19)
	at com.jetbrains.php.lang.psi.elements.impl.PhpReferenceImpl.findNamespaceName(PhpReferenceImpl.java:225)
	at com.jetbrains.php.lang.psi.elements.impl.PhpReferenceImpl.getNamespaceName(PhpReferenceImpl.java:182)
	at com.jetbrains.php.lang.psi.elements.impl.ClassReferenceImpl.getLocalFQN(ClassReferenceImpl.java:355)
	at com.jetbrains.php.lang.psi.elements.impl.ClassReferenceImpl.getFQN(ClassReferenceImpl.java:341)
	at com.jetbrains.php.lang.psi.elements.impl.PhpClassImpl.getSuperFQN(PhpClassImpl.java:407)
	at com.jetbrains.php.PhpClassHierarchyUtils.getSuperClasses(PhpClassHierarchyUtils.java:433)
	at com.jetbrains.php.lang.psi.elements.impl.PhpClassImpl.getSuperClasses(PhpClassImpl.java:425)
	at com.jetbrains.php.lang.psi.elements.impl.PhpClassImpl.getSupers(PhpClassImpl.java:724)
	at com.magento.idea.magento2plugin.linemarker.php.PluginLineMarkerProvider$PluginClassCache.getPluginsForClass(PluginLineMarkerProvider.java:98)
	at com.magento.idea.magento2plugin.linemarker.php.PluginLineMarkerProvider$PluginClassCache.getPluginsForClass(PluginLineMarkerProvider.java:99)
	at com.magento.idea.magento2plugin.linemarker.php.PluginLineMarkerProvider$PluginClassCache.getPluginsForClass(PluginLineMarkerProvider.java:99)
	at com.magento.idea.magento2plugin.linemarker.php.PluginLineMarkerProvider$PluginClassCache.getPluginsForClass(PluginLineMarkerProvider.java:99)
	at com.magento.idea.magento2plugin.linemarker.php.PluginLineMarkerProvider$PluginClassCache.getPluginsForClass(PluginLineMarkerProvider.java:99)
	at com.magento.idea.magento2plugin.linemarker.php.PluginLineMarkerProvider$PluginClassCache.getPluginsForClass(PluginLineMarkerProvider.java:99)
	at com.magento.idea.magento2plugin.linemarker.php.PluginLineMarkerProvider$PluginClassCache.getPluginsForClass(PluginLineMarkerProvider.java:99)
	at com.magento.idea.magento2plugin.linemarker.php.PluginLineMarkerProvider$PluginClassCache.getPluginsForClass(PluginLineMarkerProvider.java:99)
	at com.magento.idea.magento2plugin.linemarker.php.PluginLineMarkerProvider$PluginClassCache.getPluginsForClass(PluginLineMarkerProvider.java:99)
	at com.magento.idea.magento2plugin.linemarker.php.PluginLineMarkerProvider$PluginClassCache.getPluginsForClass(PluginLineMarkerProvider.java:99)
	at com.magento.idea.magento2plugin.linemarker.php.PluginLineMarkerProvider$PluginClassCache.getPluginsForClass(PluginLineMarkerProvider.java:99)
	at com.magento.idea.magento2plugin.linemarker.php.PluginLineMarkerProvider$PluginClassCache.getPluginsForClass(PluginLineMarkerProvider.java:99)
	at com.magento.idea.magento2plugin.linemarker.php.PluginLineMarkerProvider$PluginClassCache.getPluginsForClass(PluginLineMarkerProvider.java:99)
	at com.magento.idea.magento2plugin.linemarker.php.PluginLineMarkerProvider$PluginClassCache.getPluginsForClass(PluginLineMarkerProvider.java:99)
	at com.magento.idea.magento2plugin.linemarker.php.PluginLineMarkerProvider$PluginClassCache.getPluginsForClass(PluginLineMarkerProvider.java:99)
	at com.magento.idea.magento2plugin.linemarker.php.PluginLineMarkerProvider$PluginClassCache.getPluginsForClass(PluginLineMarkerProvider.java:99)
	at com.magento.idea.magento2plugin.linemarker.php.PluginLineMarkerProvider$PluginClassCache.getPluginsForClass(PluginLineMarkerProvider.java:99)
	at com.magento.idea.magento2plugin.linemarker.php.PluginLineMarkerProvider$PluginClassCache.getPluginsForClass(PluginLineMarkerProvider.java:99)
	at com.magento.idea.magento2plugin.linemarker.php.PluginLineMarkerProvider$PluginClassCache.getPluginsForClass(PluginLineMarkerProvider.java:99)
	at com.magento.idea.magento2plugin.linemarker.php.PluginLineMarkerProvider$PluginClassCache.getPluginsForClass(PluginLineMarkerProvider.java:99)
	at com.magento.idea.magento2plugin.linemarker.php.PluginLineMarkerProvider$PluginClassCache.getPluginsForClass(PluginLineMarkerProvider.java:99)
	at com.magento.idea.magento2plugin.linemarker.php.PluginLineMarkerProvider$PluginClassCache.getPluginsForClass(PluginLineMarkerProvider.java:99)
	at com.magento.idea.magento2plugin.linemarker.php.PluginLineMarkerProvider$PluginClassCache.getPluginsForClass(PluginLineMarkerProvider.java:99)
	at com.magento.idea.magento2plugin.linemarker.php.PluginLineMarkerProvider$PluginClassCache.getPluginsForClass(PluginLineMarkerProvider.java:99)
	at com.magento.idea.magento2plugin.linemarker.php.PluginLineMarkerProvider$PluginClassCache.getPluginsForClass(PluginLineMarkerProvider.java:99)
	at com.magento.idea.magento2plugin.linemarker.php.PluginLineMarkerProvider$PluginClassCache.getPluginsForClass(PluginLineMarkerProvider.java:99)
	at com.magento.idea.magento2plugin.linemarker.php.PluginLineMarkerProvider$PluginClassCache.getPluginsForClass(PluginLineMarkerProvider.java:99)
	at com.magento.idea.magento2plugin.linemarker.php.PluginLineMarkerProvider$PluginClassCache.getPluginsForClass(PluginLineMarkerProvider.java:99)
	at com.magento.idea.magento2plugin.linemarker.php.PluginLineMarkerProvider$PluginClassCache.getPluginsForClass(PluginLineMarkerProvider.java:99)
	at com.magento.idea.magento2plugin.linemarker.php.PluginLineMarkerProvider$PluginClassCache.getPluginsForClass(PluginLineMarkerProvider.java:99)
	at com.magento.idea.magento2plugin.linemarker.php.PluginLineMarkerProvider$PluginClassCache.getPluginsForClass(PluginLineMarkerProvider.java:99)
	at com.magento.idea.magento2plugin.linemarker.php.PluginLineMarkerProvider$PluginClassCache.getPluginsForClass(PluginLineMarkerProvider.java:99)
	at com.magento.idea.magento2plugin.linemarker.php.PluginLineMarkerProvider$PluginClassCache.getPluginsForClass(PluginLineMarkerProvider.java:99)
	at com.magento.idea.magento2plugin.linemarker.php.PluginLineMarkerProvider$PluginClassCache.getPluginsForClass(PluginLineMarkerProvider.java:99)
	at com.magento.idea.magento2plugin.linemarker.php.PluginLineMarkerProvider$PluginClassCache.getPluginsForClass(PluginLineMarkerProvider.java:99)
	at com.magento.idea.magento2plugin.linemarker.php.PluginLineMarkerProvi
```

**To Reproduce** (*)

**Expected behavior** (*)

**Screenshots**

**Please complete the following information:** (*)

 - OS: Linux 5.4.0-89-generic
 - PhpStorm/Intellij version: 2021.2.2
 - Plugin Version: 4.1.0

**Additional context**

**Comment by mdxacura2011** [comment]
> **Describe the bug** (*)
> 
> A clear and concise description of what the bug is.
> 
> ```
> java.lang.StackOverflowError
> 	at com.intellij.openapi.progress.ProgressManager.checkCanceled(ProgressManager.java:231)
> 	at com.intellij.openapi.progress.ProgressIndicatorProvider.checkCanceled(ProgressIndicatorProvider.java:23)
> 	at com.intellij.psi.impl.source.tree.CompositeElement.getPsi(CompositeElement.java:687)
> 	at com.intellij.psi.impl.source.SourceTreeToPsiMap.treeElementToPsi(SourceTreeToPsiMap.java:16)
> 	at com.intellij.psi.impl.source.tree.SharedImplUtil.getParent(SharedImplUtil.java:33)
> 	at com.intellij.extapi.psi.ASTWrapperPsiElement.getParent(ASTWrapperPsiElement.java:19)
> 	at com.jetbrains.php.lang.psi.elements.impl.PhpReferenceImpl.findNamespaceName(PhpReferenceImpl.java:225)
> 	at com.jetbrains.php.lang.psi.elements.impl.PhpReferenceImpl.getNamespaceName(PhpReferenceImpl.java:182)
> 	at com.jetbrains.php.lang.psi.elements.impl.ClassReferenceImpl.getLocalFQN(ClassReferenceImpl.java:355)
> 	at com.jetbrains.php.lang.psi.elements.impl.ClassReferenceImpl.getFQN(ClassReferenceImpl.java:341)
> 	at com.jetbrains.php.lang.psi.elements.impl.PhpClassImpl.getSuperFQN(PhpClassImpl.java:407)
> 	at com.jetbrains.php.PhpClassHierarchyUtils.getSuperClasses(PhpClassHierarchyUtils.java:433)
> 	at com.jetbrains.php.lang.psi.elements.impl.PhpClassImpl.getSuperClasses(PhpClassImpl.java:425)
> 	at com.jetbrains.php.lang.psi.elements.impl.PhpClassImpl.getSupers(PhpClassImpl.java:724)
> 	at com.magento.idea.magento2plugin.linemarker.php.PluginLineMarkerProvider$PluginClassCache.getPluginsForClass(PluginLineMarkerProvider.java:98)
> 	at com.magento.idea.magento2plugin.linemarker.php.PluginLineMarkerProvider$PluginClassCache.getPluginsForClass(PluginLineMarkerProvider.java:99)
> 	at com.magento.idea.magento2plugin.linemarker.php.PluginLineMarkerProvider$PluginClassCache.getPluginsForClass(PluginLineMarkerProvider.java:99)
> 	at com.magento.idea.magento2plugin.linemarker.php.PluginLineMarkerProvider$PluginClassCache.getPluginsForClass(PluginLineMarkerProvider.java:99)
> 	at com.magento.idea.magento2plugin.linemarker.php.PluginLineMarkerProvider$PluginClassCache.getPluginsForClass(PluginLineMarkerProvider.java:99)
> 	at com.magento.idea.magento2plugin.linemarker.php.PluginLineMarkerProvider$PluginClassCache.getPluginsForClass(PluginLineMarkerProvider.java:99)
> 	at com.magento.idea.magento2plugin.linemarker.php.PluginLineMarkerProvider$PluginClassCache.getPluginsForClass(PluginLineMarkerProvider.java:99)
> 	at com.magento.idea.magento2plugin.linemarker.php.PluginLineMarkerProvider$PluginClassCache.getPluginsForClass(PluginLineMarkerProvider.java:99)
> 	at com.magento.idea.magento2plugin.linemarker.php.PluginLineMarkerProvider$PluginClassCache.getPluginsForClass(PluginLineMarkerProvider.java:99)
> 	at com.magento.idea.magento2plugin.linemarker.php.PluginLineMarkerProvider$PluginClassCache.getPluginsForClass(PluginLineMarkerProvider.java:99)
> 	at com.magento.idea.magento2plugin.linemarker.php.PluginLineMarkerProvider$PluginClassCache.getPluginsForClass(PluginLineMarkerProvider.java:99)
> 	at com.magento.idea.magento2plugin.linemarker.php.PluginLineMarkerProvider$PluginClassCache.getPluginsForClass(PluginLineMarkerProvider.java:99)
> 	at com.magento.idea.magento2plugin.linemarker.php.PluginLineMarkerProvider$PluginClassCache.getPluginsForClass(PluginLineMarkerProvider.java:99)
> 	at com.magento.idea.magento2plugin.linemarker.php.PluginLineMarkerProvider$PluginClassCache.getPluginsForClass(PluginLineMarkerProvider.java:99)
> 	at com.magento.idea.magento2plugin.linemarker.php.PluginLineMarkerProvider$PluginClassCache.getPluginsForClass(PluginLineMarkerProvider.java:99)
> 	at com.magento.idea.magento2plugin.linemarker.php.PluginLineMarkerProvider$PluginClassCache.getPluginsForClass(PluginLineMarkerProvider.java:99)
> 	at com.magento.idea.magento2plugin.linemarker.php.PluginLineMarkerProvider$PluginClassCache.getPluginsForClass(PluginLineMarkerProvider.java:99)
> 	at com.magento.idea.magento2plugin.linemarker.php.PluginLineMarkerProvider$PluginClassCache.getPluginsForClass(PluginLineMarkerProvider.java:99)
> 	at com.magento.idea.magento2plugin.linemarker.php.PluginLineMarkerProvider$PluginClassCache.getPluginsForClass(PluginLineMarkerProvider.java:99)
> 	at com.magento.idea.magento2plugin.linemarker.php.PluginLineMarkerProvider$PluginClassCache.getPluginsForClass(PluginLineMarkerProvider.java:99)
> 	at com.magento.idea.magento2plugin.linemarker.php.PluginLineMarkerProvider$PluginClassCache.getPluginsForClass(PluginLineMarkerProvider.java:99)
> 	at com.magento.idea.magento2plugin.linemarker.php.PluginLineMarkerProvider$PluginClassCache.getPluginsForClass(PluginLineMarkerProvider.java:99)
> 	at com.magento.idea.magento2plugin.linemarker.php.PluginLineMarkerProvider$PluginClassCache.getPluginsForClass(PluginLineMarkerProvider.java:99)
> 	at com.magento.idea.magento2plugin.linemarker.php.PluginLineMarkerProvider$PluginClassCache.getPluginsForClass(PluginLineMarkerProvider.java:99)
> 	at com.magento.idea.magento2plugin.linemarker.php.PluginLineMarkerProvider$PluginClassCache.getPluginsForClass(PluginLineMarkerProvider.java:99)
> 	at com.magento.idea.magento2plugin.linemarker.php.PluginLineMarkerProvider$PluginClassCache.getPluginsForClass(PluginLineMarkerProvider.java:99)
> 	at com.magento.idea.magento2plugin.linemarker.php.PluginLineMarkerProvider$PluginClassCache.getPluginsForClass(PluginLineMarkerProvider.java:99)
> 	at com.magento.idea.magento2plugin.linemarker.php.PluginLineMarkerProvider$PluginClassCache.getPluginsForClass(PluginLineMarkerProvider.java:99)
> 	at com.magento.idea.magento2plugin.linemarker.php.PluginLineMarkerProvider$PluginClassCache.getPluginsForClass(PluginLineMarkerProvider.java:99)
> 	at com.magento.idea.magento2plugin.linemarker.php.PluginLineMarkerProvider$PluginClassCache.getPluginsForClass(PluginLineMarkerProvider.java:99)
> 	at com.magento.idea.magento2plugin.linemarker.php.PluginLineMarkerProvider$PluginClassCache.getPluginsForClass(PluginLineMarkerProvider.java:99)
> 	at com.magento.idea.magento2plugin.linemarker.php.PluginLineMarkerProvider$PluginClassCache.getPluginsForClass(PluginLineMarkerProvider.java:99)
> 	at com.magento.idea.magento2plugin.linemarker.php.PluginLineMarkerProvider$PluginClassCache.getPluginsForClass(PluginLineMarkerProvider.java:99)
> 	at com.magento.idea.magento2plugin.linemarker.php.PluginLineMarkerProvider$PluginClassCache.getPluginsForClass(PluginLineMarkerProvider.java:99)
> 	at com.magento.idea.magento2plugin.linemarker.php.PluginLineMarkerProvider$PluginClassCache.getPluginsForClass(PluginLineMarkerProvider.java:99)
> 	at com.magento.idea.magento2plugin.linemarker.php.PluginLineMarkerProvi
> ```
> 
> **To Reproduce** (*)
> 
> Steps to reproduce the behavior:
> 
> 1. Go to '...'
> 2. Click on '....'
> 3. Scroll down to '....'
> 4. See error
> 
> **Expected behavior** (*)
> 
> A clear and concise description of what you expected to happen.
> 
> **Screenshots**
> 
> If applicable, add screenshots to help explain your problem.
> 
> **Please complete the following information:** (*)
> 
> * OS: Linux 5.4.0-89-generic
> * PhpStorm/Intellij version: 2021.2.2
> * Plugin Version: 4.1.0
> 
> **Additional context**
> 
> Add any other context about the problem here.
