### ISSUE TITLE
[Bug] NullPointerException in the VersionStateManager.isValidFor

### ISSUE THREAD

**Issue by dainel-zhang** [magento/magento2-phpstorm-plugin#748]
**Describe the bug** (*)

```
java.lang.NullPointerException
	at com.magento.idea.magento2uct.versioning.VersionStateManager.isValidFor(VersionStateManager.java:87)
	at com.magento.idea.magento2uct.versioning.VersionStateManager.getInstance(VersionStateManager.java:39)
	at com.magento.idea.magento2uct.inspections.php.deprecation.ImportingDeprecatedType$1.visitPhpUseList(ImportingDeprecatedType.java:71)
	at com.jetbrains.php.lang.psi.elements.impl.PhpUseListImpl.accept(PhpUseListImpl.java:56)
	at com.jetbrains.php.lang.psi.elements.impl.PhpPsiElementImpl.accept(PhpPsiElementImpl.java:73)
	at com.magento.idea.magento2uct.inspections.UctInspectionManager.run(UctInspectionManager.java:68)
	at com.magento.idea.magento2uct.execution.GenerateUctReportCommand.lambda$execute$0(GenerateUctReportCommand.java:117)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:828)
	at com.magento.idea.magento2uct.execution.GenerateUctReportCommand.lambda$execute$2(GenerateUctReportCommand.java:101)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:265)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.base/java.lang.Thread.run(Thread.java:829)

```

**To Reproduce** (*)

**Expected behavior** (*)

**Screenshots**

**Please complete the following information:** (*)

 - OS: Windows 10 10.0
 - PhpStorm/Intellij version: 2021.2.3
 - Plugin Version: 4.1.0

**Additional context**

**Comment by bohdan-harniuk** [comment]
Hello, @dainel-zhang!

It should be already fixed.
Could you please update plugin to the last 4.2.0 version and clarify if everything is fine?

Thank you in advance!

**Comment by bohdan-harniuk** [comment]
Hello, @dainel-zhang!

I am waiting for your reply.

Thank you in advance!

**Comment by bohdan-harniuk** [comment]
Hello, @dainel-zhang!

If you will get this issue again, you can report about it.
But most likely everything has already been fixed.
Please, update your plugin to the latest available version.

Thanks,
Bohdan
