### ISSUE TITLE
[Bug] java.lang.Throwable: when an IOException is thrown during new plugin generation

### ISSUE THREAD

**Issue by amarroni** [magento/magento2-phpstorm-plugin#760]
**Describe the bug** (*)

```
java.lang.Throwable: AWT events are not allowed inside write action: java.awt.event.FocusEvent[FOCUS_LOST,temporary,opposite=javax.swing.JButton[,203,11,78x30,alignmentX=0.0,alignmentY=0.5,border=com.intellij.ide.ui.laf.darcula.ui.DarculaButtonPainter@4e6780fc,flags=424,maximumSize=,minimumSize=,preferredSize=java.awt.Dimension[width=78,height=30],defaultIcon=,disabledIcon=,disabledSelectedIcon=,margin=com.intellij.util.ui.JBInsets[top=0,left=0,bottom=0,right=0],paintBorder=true,paintFocus=true,pressedIcon=,rolloverEnabled=false,rolloverIcon=,rolloverSelectedIcon=,selectedIcon=,text=OK,defaultCapable=true],cause=ACTIVATION] on javax.swing.JButton[,0,0,78x30,alignmentX=0.0,alignmentY=0.5,border=com.intellij.ide.ui.laf.darcula.ui.DarculaButtonPainter@4e6780fc,flags=296,maximumSize=,minimumSize=,preferredSize=,defaultIcon=,disabledIcon=,disabledSelectedIcon=,margin=com.intellij.util.ui.JBInsets[top=0,left=0,bottom=0,right=0],paintBorder=true,paintFocus=true,pressedIcon=,rolloverEnabled=false,rolloverIcon=,rolloverSelectedIcon=,selectedIcon=,text=OK,defaultCapable=true]
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:182)
	at com.intellij.openapi.application.impl.NoSwingUnderWriteAction.lambda$watchForEvents$0(NoSwingUnderWriteAction.java:22)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$7(IdeEventQueue.java:461)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:794)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:492)
	at java.desktop/java.awt.SentEvent.dispatch(SentEvent.java:70)
	at java.desktop/java.awt.DefaultKeyboardFocusManager$DefaultKeyboardFocusManagerSentEvent.dispatch(DefaultKeyboardFocusManager.java:254)
	at java.desktop/java.awt.DefaultKeyboardFocusManager.sendMessage(DefaultKeyboardFocusManager.java:281)
	at java.desktop/java.awt.DefaultKeyboardFocusManager.dispatchEvent(DefaultKeyboardFocusManager.java:801)
	at com.intellij.ide.IdeKeyboardFocusManager.dispatchEvent(IdeKeyboardFocusManager.java:42)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:4908)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2321)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2784)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4859)
	at java.desktop/sun.lwawt.LWWindowPeer.lambda$changeFocusedWindow$8(LWWindowPeer.java:1394)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:751)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:749)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:748)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:885)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:754)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$6(IdeEventQueue.java:441)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:825)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$7(IdeEventQueue.java:440)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:794)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:492)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:117)
	at java.desktop/java.awt.WaitDispatchSupport$2.run(WaitDispatchSupport.java:190)
	at java.desktop/java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:235)
	at java.desktop/java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:233)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.desktop/java.awt.WaitDispatchSupport.enter(WaitDispatchSupport.java:233)
	at java.desktop/java.awt.Dialog.show(Dialog.java:1063)
	at com.intellij.openapi.ui.impl.DialogWrapperPeerImpl$MyDialog.show(DialogWrapperPeerImpl.java:699)
	at com.intellij.openapi.ui.impl.DialogWrapperPeerImpl.show(DialogWrapperPeerImpl.java:435)
	at com.intellij.openapi.ui.DialogWrapper.doShow(DialogWrapper.java:1726)
	at com.intellij.openapi.ui.DialogWrapper.show(DialogWrapper.java:1685)
	at com.intellij.openapi.ui.messages.AlertMessagesManager.showMessageDialog(AlertMessagesManager.kt:117)
	at com.intellij.ui.messages.MessagesServiceImpl.showMessageDialog(MessagesServiceImpl.java:58)
	at com.jetbrains.rdserver.ui.BackendMessagesService.showMessageDialog(BackendMessagesService.kt:28)
	at com.intellij.openapi.ui.Messages.showErrorDialog(Messages.java:661)
	at com.intellij.openapi.ui.Messages.showErrorDialog(Messages.java:688)
	at com.magento.idea.magento2plugin.actions.generation.generator.util.FileFromTemplateGenerator.generate(FileFromTemplateGenerator.java:77)
	at com.magento.idea.magento2plugin.actions.generation.generator.PluginClassGenerator.createPluginClass(PluginClassGenerator.java:219)
	at com.magento.idea.magento2plugin.actions.generation.generator.PluginClassGenerator.lambda$generate$0(PluginClassGenerator.java:99)
	at com.intellij.openapi.command.WriteCommandAction.lambda$runWriteCommandAction$4(WriteCommandAction.java:348)
	at com.intellij.openapi.command.WriteCommandAction$BuilderImpl.lambda$doRunWriteCommandAction$1(WriteCommandAct
```

**To Reproduce** (*)

**Expected behavior** (*)

**Screenshots**

**Please complete the following information:** (*)

 - OS: Mac OS X 12.0.1
 - PhpStorm/Intellij version: 2021.2.3
 - Plugin Version: 4.1.0

**Additional context**

**Comment by bohdan-harniuk** [comment]
Hello, @amarroni!
Thank you for your report!

We'll try to fix it in the next bug-fix release.

Thanks,
Bohdan

**Comment by bohdan-harniuk** [comment]
Hello, @amarroni!

You didn't provide steps to reproduce and code samples, so I was trying to reproduce it by provided stack trace.
Unfortunately I couldn't find out why you had this problem. So I made an exception programmatically to get this error.

<img width="1139" alt="Screenshot 2021-12-17 at 22 30 58" src="https://user-images.githubusercontent.com/31848341/146604754-509709d6-b579-45d1-a3ea-36faca832fac.png">

The fact is that this window, with a detailed error, should not be displayed:

<img width="378" alt="Screenshot 2021-12-17 at 22 36 30" src="https://user-images.githubusercontent.com/31848341/146605020-4a542338-7436-4a65-a808-44befbaa8ab8.png">

 , as there is another window with an error:

![Uploading Screenshot 2021-12-17 at 22.36.39.png…]()

We will fix this error and it will be delivered in the upcoming release, 4.2.2.

Thanks, Bohdan

**Comment by bohdan-harniuk** [comment]
@amarroni

The bug is fixed. Now, if you will be faced with a such exception, you wont see critical exception and multiple error dialogs.
Instead of it you will see single popup with error message. If additional information is available, you will see error dialog with it:

<img width="687" alt="Screenshot 2021-12-17 at 23 33 23" src="https://user-images.githubusercontent.com/31848341/146612024-f766d657-ae9d-4b85-a9b3-58d34fc880cb.png">

Thank you again for reporting this issue!

Fix will be delivered in the upcoming release, 4.2.2.
