### ISSUE TITLE
Bug Report 2021/11/16

### ISSUE THREAD

**Issue by igortregub** [magento/magento2-phpstorm-plugin#765]
**Describe the bug** (*)

```
java.lang.StackOverflowError
	at com.intellij.util.CachedValueBase.isDependencyOutOfDate(CachedValueBase.java:124)
	at com.intellij.psi.impl.PsiCachedValue.isDependencyOutOfDate(PsiCachedValue.java:112)
	at com.intellij.util.CachedValueBase.isUpToDate(CachedValueBase.java:114)
	at com.intellij.psi.impl.PsiCachedValue.isUpToDate(PsiCachedValue.java:106)
	at com.intellij.util.CachedValueBase.checkUpToDate(CachedValueBase.java:97)
	at com.intellij.util.CachedValueBase.getUpToDateOrNull(CachedValueBase.java:93)
	at com.intellij.util.CachedValueBase.getValueWithLock(CachedValueBase.java:217)
	at com.intellij.psi.impl.PsiCachedValueImpl.getValue(PsiCachedValueImpl.java:28)
	at com.jetbrains.php.lang.psi.elements.impl.PhpNamespaceReferenceImpl.getFullName(PhpNamespaceReferenceImpl.java:48)
	at com.jetbrains.php.lang.psi.elements.impl.PhpReferenceImpl.getImmediateNamespaceName(PhpReferenceImpl.java:176)
	at com.jetbrains.php.lang.psi.elements.impl.PhpReferenceImpl.isAbsolute(PhpReferenceImpl.java:187)
	at com.jetbrains.php.lang.psi.elements.impl.ClassReferenceImpl.resolveLocal(ClassReferenceImpl.java:220)
	at com.jetbrains.php.lang.psi.elements.impl.ClassReferenceImpl.getLocalFQN(ClassReferenceImpl.java:346)
	at com.jetbrains.php.lang.psi.elements.impl.ClassReferenceImpl.getFQN(ClassReferenceImpl.java:341)
	at com.jetbrains.php.lang.psi.elements.impl.PhpClassImpl.getSuperFQN(PhpClassImpl.java:407)
	at com.jetbrains.php.PhpClassHierarchyUtils.getSuperClasses(PhpClassHierarchyUtils.java:433)
	at com.jetbrains.php.lang.psi.elements.impl.PhpClassImpl.getSuperClasses(PhpClassImpl.java:425)
	at com.jetbrains.php.lang.psi.elements.impl.PhpClassImpl.getSupers(PhpClassImpl.java:724)
	at com.magento.idea.magento2plugin.linemarker.php.PluginLineMarkerProvider$PluginClassCache.getPluginsForClass(PluginLineMarkerProvider.java:98)
	at com.magento.idea.magento2plugin.linemarker.php.PluginLineMarkerProvider$PluginClassCache.getPluginsForClass(PluginLineMarkerProvider.java:99)
	at com.magento.idea.magento2plugin.linemarker.php.PluginLineMarkerProvider$PluginClassCache.getPluginsForClass(PluginLineMarkerProvider.java:99)
	at com.magento.idea.magento2plugin.linemarker.php.PluginLineMarkerProvider$PluginClassCache.getPluginsForClass(PluginLineMarkerProvider.java:99)
	at com.magento.idea.magento2plugin.linemarker.php.PluginLineMarkerProvider$PluginClassCache.getPluginsForClass(PluginLineMarkerProvider.java:99)
	at com.magento.idea.magento2plugin.linemarker.php.PluginLineMarkerProvider$PluginClassCache.getPluginsForClass(PluginLineMarkerProvider.java:99)
	at com.magento.idea.magento2plugin.linemarker.php.PluginLineMarkerProvider$PluginClassCache.getPluginsForClass(PluginLineMarkerProvider.java:99)
	at com.magento.idea.magento2plugin.linemarker.php.PluginLineMarkerProvider$PluginClassCache.getPluginsForClass(PluginLineMarkerProvider.java:99)
	at com.magento.idea.magento2plugin.linemarker.php.PluginLineMarkerProvider$PluginClassCache.getPluginsForClass(PluginLineMarkerProvider.java:99)
	at com.magento.idea.magento2plugin.linemarker.php.PluginLineMarkerProvider$PluginClassCache.getPluginsForClass(PluginLineMarkerProvider.java:99)
	at com.magento.idea.magento2plugin.linemarker.php.PluginLineMarkerProvider$PluginClassCache.getPluginsForClass(PluginLineMarkerProvider.java:99)
	at com.magento.idea.magento2plugin.linemarker.php.PluginLineMarkerProvider$PluginClassCache.getPluginsForClass(PluginLineMarkerProvider.java:99)
	at com.magento.idea.magento2plugin.linemarker.php.PluginLineMarkerProvider$PluginClassCache.getPluginsForClass(PluginLineMarkerProvider.java:99)
	at com.magento.idea.magento2plugin.linemarker.php.PluginLineMarkerProvider$PluginClassCache.getPluginsForClass(PluginLineMarkerProvider.java:99)
	at com.magento.idea.magento2plugin.linemarker.php.PluginLineMarkerProvider$PluginClassCache.getPluginsForClass(PluginLineMarkerProvider.java:99)
	at com.magento.idea.magento2plugin.linemarker.php.PluginLineMarkerProvider$PluginClassCache.getPluginsForClass(PluginLineMarkerProvider.java:99)
	at com.magento.idea.magento2plugin.linemarker.php.PluginLineMarkerProvider$PluginClassCache.getPluginsForClass(PluginLineMarkerProvider.java:99)
	at com.magento.idea.magento2plugin.linemarker.php.PluginLineMarkerProvider$PluginClassCache.getPluginsForClass(PluginLineMarkerProvider.java:99)
	at com.magento.idea.magento2plugin.linemarker.php.PluginLineMarkerProvider$PluginClassCache.getPluginsForClass(PluginLineMarkerProvider.java:99)
	at com.magento.idea.magento2plugin.linemarker.php.PluginLineMarkerProvider$PluginClassCache.getPluginsForClass(PluginLineMarkerProvider.java:99)
	at com.magento.idea.magento2plugin.linemarker.php.PluginLineMarkerProvider$PluginClassCache.getPluginsForClass(PluginLineMarkerProvider.java:99)
	at com.magento.idea.magento2plugin.linemarker.php.PluginLineMarkerProvider$PluginClassCache.getPluginsForClass(PluginLineMarkerProvider.java:99)
	at com.magento.idea.magento2plugin.linemarker.php.PluginLineMarkerProvider$PluginClassCache.getPluginsForClass(PluginLineMarkerProvider.java:99)
	at com.magento.idea.magento2plugin.linemarker.php.PluginLineMarkerProvider$PluginClassCache.getPluginsForClass(PluginLineMarkerProvider.java:99)
	at com.magento.idea.magento2plugin.linemarker.php.PluginLineMarkerProvider$PluginClassCache.getPluginsForClass(PluginLineMarkerProvider.java:99)
	at com.magento.idea.magento2plugin.linemarker.php.PluginLineMarkerProvider$PluginClassCache.getPluginsForClass(PluginLineMarkerProvider.java:99)
	at com.magento.idea.magento2plugin.linemarker.php.PluginLineMarkerProvider$PluginClassCache.getPluginsForClass(PluginLineMarkerProvider.java:99)
	at com.magento.idea.magento2plugin.linemarker.php.PluginLineMarkerProvider$PluginClassCache.getPluginsForClass(PluginLineMarkerProvider.java:99)
	at com.magento.idea.magento2plugin.linemarker.php.PluginLineMarkerProvider$PluginClassCache.getPluginsForClass(PluginLineMarkerProvider.java:99)
	at com.magento.idea.magento2plugin.linemarker.php.PluginLineMarkerProvider$PluginClassCache.getPluginsForClass(PluginLineMarkerProvider.java:99)
	at com.magento.idea.magento2plugin.linemarker.php.PluginLineMarkerProvider$PluginClassCache.getPluginsForClass(PluginLineMarkerProvider.java:99)
	at com.magento.idea.magento2plugin.linemarker.php.PluginLineMarkerProvider$PluginClassCache.getPluginsForClass(PluginLineMarkerProvider.java:99)
	at com.magento.idea.magento2plugin.linemarker.php.PluginLineMarkerProvider$PluginClassCache.getPluginsForClass(PluginLineMarkerProvider.java:99)
	at com.magento.idea.magento2plugin.linemarke
```

**To Reproduce** (*)

**Expected behavior** (*)

**Screenshots**

**Please complete the following information:** (*)

 - OS: Mac OS X 11.6
 - PhpStorm/Intellij version: 2021.2.3
 - Plugin Version: 4.1.0

**Additional context**

**Comment by bohdan-harniuk** [comment]
Hello, @igortregub!

Thank you for your report!
We'll try to deliver fix in the next bug-fix release!

Thank you!

**Comment by bohdan-harniuk** [comment]
Hello, @igortregub!

I've reproduced this bug in the next way:

1. created new class A
2. created new class B
3. added plugins for class A
4. made class A extends class B
5. made class B extends class A

I know, it doesn't have any sense, but it was only way to reproduce this bug.

cc. @ConradoSM, @anvasiliev, @lucthanca, @magentopits, @sadlig, @zakharevych, @anhphuoc

If anyone could add additional steps to reproduce this bug, please provide it here! 
It will help to cover more cases here.

Thanks,
Bohdan

**Comment by bohdan-harniuk** [comment]
This issue will be reopened if any additional steps to reproduce info is provided and it is not covered by the related PR.
