### ISSUE TITLE
[Bug] StringIndexOutOfBoundsException during UCT inspection via action execution

### ISSUE THREAD

**Issue by karyna-tsymbal-atwix** [magento/magento2-phpstorm-plugin#810]
**Describe the bug** (*)

```
java.lang.StringIndexOutOfBoundsException: begin 0, end 39, length 38
	at java.base/java.lang.String.checkBoundsBeginEnd(String.java:3319)
	at java.base/java.lang.String.substring(String.java:1874)
	at com.magento.idea.magento2uct.util.php.MagentoTypeEscapeUtil.escape(MagentoTypeEscapeUtil.java:35)
	at com.magento.idea.magento2uct.versioning.VersionStateManager.escapeFqn(VersionStateManager.java:186)
	at com.magento.idea.magento2uct.versioning.VersionStateManager.isDeprecated(VersionStateManager.java:62)
	at com.magento.idea.magento2uct.inspections.php.deprecation.CallingDeprecatedMethod.execute(CallingDeprecatedMethod.java:31)
	at com.magento.idea.magento2uct.inspections.php.CallMethodInspection$1.visitPhpMethodReference(CallMethodInspection.java:43)
	at com.jetbrains.php.lang.psi.elements.impl.MethodReferenceImpl.accept(MethodReferenceImpl.java:44)
	at com.jetbrains.php.lang.psi.elements.impl.PhpASTElementImpl.accept(PhpASTElementImpl.java:26)
	at com.magento.idea.magento2uct.inspections.UctInspectionManager.run(UctInspectionManager.java:69)
	at com.magento.idea.magento2uct.execution.GenerateUctReportCommand.lambda$execute$0(GenerateUctReportCommand.java:120)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:828)
	at com.magento.idea.magento2uct.execution.GenerateUctReportCommand.lambda$execute$2(GenerateUctReportCommand.java:104)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:265)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.base/java.lang.Thread.run(Thread.java:829)

```

**To Reproduce** (*)

**Expected behavior** (*)

**Screenshots**

**Please complete the following information:** (*)

 - OS: Mac OS X 11.6
 - PhpStorm/Intellij version: 2021.2.2
 - Plugin Version: 4.2.0

**Additional context**

**Comment by bohdan-harniuk** [comment]
Hello, @karyna-tsymbal-atwix !

Thank you for your report!
We'll deliver fix in the next bug-fix release!

Thank you!

**Comment by bohdan-harniuk** [comment]
Hello, @karyna-tsymbal-atwix!

I've fixed this bug.
Could you please verify it in your ENV?

Thanks, 
Bohdan!

**Comment by karyna-tsymbal-atwix** [comment]
Hi @bohdan-harniuk , I re-checked with a 4.2.2 plugin version on the same project - everything is working fine. Thanks for the fix!

**Comment by bohdan-harniuk** [comment]
Hi, @karyna-tsymbal-atwix!

Thank you for your assistance!
