### ISSUE TITLE
[Bug] IllegalArgumentException: URLDecoder: Incomplete trailing escape (%) pattern

### ISSUE THREAD

**Issue by panthervsanyone** [magento/magento2-phpstorm-plugin#842]
**Describe the bug** (*)

```
java.lang.IllegalArgumentException: URLDecoder: Incomplete trailing escape (%) pattern
	at java.base/java.net.URLDecoder.decode(URLDecoder.java:225)
	at com.magento.idea.magento2plugin.project.diagnostic.github.GitHubNewIssueBodyBuilderUtil.decode(GitHubNewIssueBodyBuilderUtil.java:133)
	at com.magento.idea.magento2plugin.project.diagnostic.github.GitHubNewIssueBodyBuilderUtil.buildNewBugReportBody(GitHubNewIssueBodyBuilderUtil.java:60)
	at com.magento.idea.magento2plugin.project.diagnostic.github.GitHubNewIssueUrlBuilderUtil.buildNewBugIssueUrl(GitHubNewIssueUrlBuilderUtil.java:39)
	at com.magento.idea.magento2plugin.project.diagnostic.DefaultErrorReportSubmitter.submit(DefaultErrorReportSubmitter.java:73)
	at com.intellij.diagnostic.IdeErrorsDialog.reportMessage(IdeErrorsDialog.java:632)
	at com.intellij.diagnostic.IdeErrorsDialog.reportAll(IdeErrorsDialog.java:1102)
	at com.intellij.diagnostic.IdeErrorsDialog$ReportAndClearAllAction.actionPerformed(IdeErrorsDialog.java:1086)
	at com.intellij.diagnostic.IdeErrorsDialog$CompositeAction.actionPerformed(IdeErrorsDialog.java:993)
	at java.desktop/javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1967)
	at java.desktop/javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2308)
	at java.desktop/javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:405)
	at java.desktop/javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:262)
	at java.desktop/javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:270)
	at java.desktop/java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:297)
	at java.desktop/java.awt.Component.processMouseEvent(Component.java:6654)
	at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3345)
	at java.desktop/java.awt.Component.processEvent(Component.java:6419)
	at java.desktop/java.awt.Container.processEvent(Container.java:2263)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5029)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2321)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4861)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4918)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4547)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4488)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2307)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2790)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4861)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:778)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:751)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:749)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:748)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:891)
	at com.intellij.ide.IdeEventQueue.dispatchMouseEvent(IdeEventQueue.java:820)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:757)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$6(IdeEventQueue.java:447)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:818)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$7(IdeEventQueue.java:446)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:805)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:498)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

```

**To Reproduce** (*)

**Expected behavior** (*)

**Screenshots**

**Please complete the following information:** (*)

 - OS: Linux 5.11.0-41-generic
 - PhpStorm/Intellij version: 2021.3
 - Plugin Version: 4.2.0

**Additional context**

**Comment by bohdan-harniuk** [comment]
I've successfully reproduced this issue.

**To Reproduce** (*)

Steps to reproduce the behavior:
1. Create new message queue
2. Try to create another message queue with the same handler class
3. Raised an **exception num. 1**: should be fixed in the scope of this task
4. Try to click on the "Report Me" button
5. Raised an **exception num. 2**: the main problem of this issue

**Exception num. 1:**

<img width="769" alt="Screenshot 2021-12-22 at 20 57 13" src="https://user-images.githubusercontent.com/31848341/147141770-2001a97e-b981-4f42-9b66-7d5c519399c5.png">
<img width="769" alt="Screenshot 2021-12-22 at 21 02 18" src="https://user-images.githubusercontent.com/31848341/147142287-d46f6f40-7043-436b-9c43-37a47d864438.png">
<img width="1152" alt="Screenshot 2021-12-22 at 21 02 36" src="https://user-images.githubuserconte
nt.com/31848341/147142313-e8675266-d40f-4916-bb80-9196c938bc70.png">

**Exception num. 2:**

<img width="1152" alt="Screenshot 2021-12-22 at 21 03 30" src="https://user-images.githubusercontent.com/31848341/147142429-f789d8ae-5e16-4d64-bde5-991c4867ffc7.png">

**Comment by Iamwade** [comment]
@magento I am working on this
