### ISSUE TITLE
Bug Report 2022/02/08

### ISSUE THREAD

**Issue by igi8819** [magento/magento2-phpstorm-plugin#964]
**Describe the bug** (*)

```
com.intellij.openapi.vfs.InvalidVirtualFileAccessException: Accessing invalid virtual file: file:///var/www/html/lindt-na/var/cache/mage--5; original:747334; found:747334; File.exists()=false
	at com.intellij.openapi.vfs.newvfs.impl.VirtualDirectoryImpl.handleInvalidDirectory(VirtualDirectoryImpl.java:191)
	at com.intellij.openapi.vfs.newvfs.impl.VirtualDirectoryImpl.doFindChild(VirtualDirectoryImpl.java:112)
	at com.intellij.openapi.vfs.newvfs.impl.VirtualDirectoryImpl.findChild(VirtualDirectoryImpl.java:78)
	at com.intellij.openapi.vfs.newvfs.impl.VirtualDirectoryImpl.doFindChildById(VirtualDirectoryImpl.java:548)
	at com.intellij.openapi.vfs.newvfs.persistent.FSRecords$1ParentFinder.findChild(FSRecords.java:460)
	at com.intellij.openapi.vfs.newvfs.persistent.FSRecords$1ParentFinder.findDescendantByIdPath(FSRecords.java:452)
	at com.intellij.openapi.vfs.newvfs.persistent.FSRecords.findFileById(FSRecords.java:471)
	at com.intellij.openapi.vfs.newvfs.persistent.PersistentFSImpl.findFileById(PersistentFSImpl.java:1399)
	at com.intellij.openapi.vfs.newvfs.persistent.PersistentFSImpl.findFileByIdIfCached(PersistentFSImpl.java:1404)
	at com.intellij.psi.stubs.StubIndexImplUtil$1.findNext(StubIndexImplUtil.java:35)
	at com.intellij.psi.stubs.StubIndexImplUtil$1.<init>(StubIndexImplUtil.java:21)
	at com.intellij.psi.stubs.StubIndexImplUtil.mapIdIterator(StubIndexImplUtil.java:17)
	at com.intellij.psi.stubs.StubIndexImpl.processElements(StubIndexImpl.java:310)
	at com.intellij.psi.stubs.StubIndex.getElements(StubIndex.java:100)
	at com.intellij.psi.stubs.StubIndex.getElements(StubIndex.java:88)
	at com.jetbrains.php.PhpIndexImpl.getElements(PhpIndexImpl.java:574)
	at com.jetbrains.php.PhpIndexImpl.getByName(PhpIndexImpl.java:992)
	at com.jetbrains.php.PhpIndexImpl.getByFQN(PhpIndexImpl.java:967)
	at com.jetbrains.php.PhpIndexImpl.getClassesByFQNInternal(PhpIndexImpl.java:1042)
	at com.jetbrains.php.PhpIndexImpl.getAnyByFQN(PhpIndexImpl.java:1079)
	at com.jetbrains.php.lang.psi.elements.impl.PhpClassAliasImpl.computeOriginalClass(PhpClassAliasImpl.kt:44)
	at com.jetbrains.php.lang.psi.elements.impl.PhpClassAliasImpl.getOriginalClassInternal(PhpClassAliasImpl.kt:57)
	at com.jetbrains.php.lang.psi.elements.impl.PhpClassAliasImpl.getOriginal(PhpClassAliasImpl.kt:54)
	at com.jetbrains.php.lang.psi.elements.impl.PhpClassAliasImpl.isInterface(PhpClassAliasImpl.kt:109)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:176)
	at java.base/java.util.AbstractList$RandomAccessSpliterator.forEachRemaining(AbstractList.java:720)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:550)
	at java.base/java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:260)
	at java.base/java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:517)
	at one.util.streamex.AbstractStreamEx.toArray(AbstractStreamEx.java:389)
	at one.util.streamex.AbstractStreamEx.toList(AbstractStreamEx.java:1313)
	at com.jetbrains.php.lang.classAlias.PhpClassAliasIndexImpl.getAliasesByName(PhpClassAliasIndexImpl.java:134)
	at com.jetbrains.php.lang.classAlias.PhpClassAliasIndexImpl.getAliasNames(PhpClassAliasIndexImpl.java:67)
	at com.jetbrains.php.lang.classAlias.PhpClassAliasIndexImpl.getInterfaceNames(PhpClassAliasIndexImpl.java:48)
	at com.jetbrains.php.PhpIndexImpl.getAllInterfaceNames(PhpIndexImpl.java:426)
	at com.magento.idea.magento2plugin.completion.provider.PhpClassCompletionProvider.addCompletions(PhpClassCompletionProvider.java:90)
	at com.intellij.codeInsight.completion.CompletionProvider.addCompletionVariants(CompletionProvider.java:34)
	at com.intellij.codeInsight.completion.CompletionContributor.fillCompletionVariants(CompletionContributor.java:156)
	at com.intellij.codeInsight.completion.CompletionService.getVariantsFromContributors(CompletionService.java:77)
	at com.intellij.codeInsight.completion.CompletionResultSet.runRemainingContributors(CompletionResultSet.java:154)
	at com.intellij.codeInsight.completion.CompletionResultSet.runRemainingContributors(CompletionResultSet.java:146)
	at com.intellij.codeInsight.completion.CompletionResultSet.runRemainingContributors(CompletionResultSet.java:142)
	at com.intellij.codeInsight.completion.CompletionResultSet.runRemainingContributors(CompletionResultSet.java:132)
	at com.intellij.codeInsight.completion.XmlNoVariantsDelegator.fillCompletionVariants(XmlNoVariantsDelegator.java:12)
	at com.intellij.codeInsight.completion.CompletionService.getVariantsFromContributors(CompletionService.java:77)
	at com.intellij.codeInsight.completion.CompletionResultSet.runRemainingContributors(CompletionResultSet.java:154)
	at com.intellij.codeInsight.completion.CompletionResultSet.runRemainingContributors(CompletionResultSet.java:146)
	at com.intellij.codeInsight.completion.CompletionResultSet.runRemainingContributors(CompletionResultSet.java:142)
	at com.intellij.codeInsight.template.impl.LiveTemplateCompletionContributor$1.addCompletions(LiveTemplateCompletionContributor.java:89)
	at com.intellij.codeInsight.completion.CompletionProvider.addCompletionVariants(CompletionProvider.java:34)
	at com.intellij.codeInsight.completion.CompletionContributor.fillCompletionVariants(CompletionContributor.java:156)
	at com.intellij.codeInsight.completion.CompletionService.getVariantsFromContributors(CompletionService.java:77)
	at com.intellij.codeInsight.completion.CompletionResultSet.runRemainingContributors(CompletionResultSet.java:154)
	at com.intellij.codeInsight.completion.CompletionResultSet.runRemainingContributors(CompletionResultSet.java:146)
	at com.intellij.codeInsight.completion.CompletionResultSet.runRemainingContributors(CompletionResultSet.java:142)
	at com.intellij.codeInsight.completion.XmlCompletionContributor$3.addCompletions(XmlCompletionContributor.java:127)
	at com.intellij.codeInsight.completion.CompletionProvider.addCompletionVariants(CompletionProvider.java:34)
	at com.intellij.codeInsight.completion.CompletionContributor.fillCompletionVariants(CompletionContributor.java:156)
	at com.intellij.codeInsight.completion.XmlCompletionContributor.fillCompletionVariants(XmlCompletionContributor.java:182)
	at com.intellij.codeInsight.completion.CompletionService.getV
```

**To Reproduce** (*)

**Expected behavior** (*)

**Screenshots**

**Please complete the following information:** (*)

 - OS: Linux 5.4.0-81-generic
 - PhpStorm/Intellij version: 2021.2.4
 - Plugin Version: 4.2.2

**Additional context**

**Comment by bohdan-harniuk** [comment]
Or any other file in which this exception was raised.

**Comment by igi8819** [comment]
@bohdan-harniuk 
Sorry, i can not find mage-5 file now, probably deleted...
but i did not get this issue now, i got this when i created a new module (copyied from another module and without using this extension)

**Comment by bohdan-harniuk** [comment]
@igi8819, thank you for details!

I'll try to reproduce this issue.

**Comment by doninAtwix** [comment]
@magento I am working on this

**Comment by doninAtwix** [comment]
Hi @igi8819 .
Can you try again to reproduce the error, remember the steps you did and write here?

My steps to reproduce the error:
1. Download module archive and unpack it
2. Copy unpacked module
3. Paste it via ide to app/code folder
Are these the right steps?

Thank you

**Comment by doninAtwix** [comment]
Hello @igi8819 .
Can you help me with reproduce this issue?

Thank you

**Comment by bohdan-harniuk** [comment]
Hello, @igi8819!

Please, assist us with the bug reproducing. Any help will be appreciated.

Regards,

**Comment by igi8819** [comment]
Hi @bohdan-harniuk 
sorry for late answer, i was busy these days,
I tried with @doninAtwix recommendation, but i can not replicate.

As i remember i go this issue when i copied a composer module from vendor into app/code, without deleting module from vendor.

You can close this ticket if you can not replicate.

**Comment by bohdan-harniuk** [comment]
Hello, @igi8819!

Thank you for your help here!
If you will face this problem again, please, reopen this ticket with the additional information about reproducing.

cc. @doninAtwix, thank you for your work here!

Regards,
